# Tutorial 6: Mixed Precision Quantization Search with Mase and Optuna

In this tutorial, we'll see how Mase can be integrated with Optuna, the popular hyperparameter optimization framework, to search for a Bert model optimized for sequence classification on the IMDb dataset. We'll take the Optuna-generated model and import it into Mase, then run the CompressionPipeline to prepare the model for edge deployment by quantizing and pruning its weights.

As we'll see, running Architecture Search with Mase/Optuna involves the following steps.

1. **Define the search space**: this is a dictionary containing the range of values for each parameter at each layer in the model.

2. **Write the model constructor**: this is a function which uses Optuna utilities to sample a model from the search space, and constructs the model using transformers from_config class method.

3. **Write the objective function**: this function calls on the model constructor defined in Step 2 and defines the training/evaluation setup for each search iteration.

4. **Go!** Choose an Optuna sampler, create a study and launch the search.

# Quantizers

## Software-simulated quantization

| name | paper | model@dataset | blocking dimension | representation | extra |
| --- | --- | --- | --- | --- | --- |
| `integer_quantizer(x, width, frac_width)` | - | - | - | $(i/2^{f})$, <br> signed int $i$, the number of fractional bits $f$ | signed fixed-point number |
| `minifloat_denorm_quantizer(x, width, exponent_width, exponent_bias)` | - | - | - | $(-1)^s 2^e m$, <br> exponent $e$, mantissa $m$ | no implicit leading bit in mantissa|
| `minifloat_ieee_quantizer(x, width, exponent_width, exponent_bias)` | - | - | - | $(-1)^s 2^e m'$, <br> normal: $m'=1.0+m$, subnormal: $m'=m$ | an implicit leading bit in mantissa |
| `log_quantizer(x, width, exponent_bias)` | [CNNs using Logarithmic Data Representation](http://arxiv.org/abs/1603.01025) | VGG16@CIFAR10, ALEXNET@CIFAR10 | - | $(-1)^s 2^e$ | - |
| `msfp_quatizer(x, width, exponent_width, exponent_bias, block_size)`| [Microsoft MSFP](https://proceedings.neurips.cc/paper/2020/hash/747e32ab0fea7fbd2ad9ec03daa3f840-Abstract.html) | CNNs, RNNs, <br> Transformers (BERT@MRPC, BERT@SQuAD1.1, BERT@SQuADv2) | Linear matrix: tiles along matrix row, <br> Conv2D: tiles along channel depth | $2^{e_{shared}}[(-1)^{s_1} m_1, (-1)^{s_2} m_2, \dots]$ |
| `block_minifloat_quantizer(x, width, exponent_width, bias_width, block_size)` | [Philip Leong's Block Minifloat](https://openreview.net/forum?id=6zaTwpNSsQ2) | CNNs, RNNs, Transformer (Transformer-base@IWSLT) | Matrix Multiply: $N\times N$ square block. <br> Conv2D (?) | $2^{-b_{shared}}[(-1)^{s_1} 2^{e'_1}m'_1, (-1)^{s_2}2^{e'_2}m'_2, \dots]$,  <br> the shared exponent bias:$b_{shared}$|  both forward and backward uses software-simulated quantized values|
| `block_log_quantizer(x, width, exponent_bias_width, block_size)` | - | - | - | $2^{-b_{shared}}[(-1)^{s_1} 2^{e'_1}, (-1)^{s_2}2^{e'_2}, \dots]$, <br> the shared exponent bias $b_{shared}$ |  |

The following quantizers are not supported yet

| name | paper | model@dataset | blocking dimension | representation | extra |
| --- | --- | --- | --- | --- | --- |
| ⬜ TODO: `mx_quantizer` | [Microsoft's MX](https://arxiv.org/abs/2302.08007) | See Table III in the paper. CNNs, RNNs, ViT (DeiT-Tiny/-Small@ImageNet), <br> Transformer (Transformer-base/-large@WMT-17, BERT-base/-large@Wikipedia, GPT-XS/-S/-M/-L/-XL@?) | Two-level scaling on vectors | $2^{e_{s}}\Big[ 2^{e_{ss_1}} [(-1)^{s_1} m_1, (-1)^{s_2} m_2  ], 2^{e_{ss_2}}[(-1)^{s_3} m_3, (-1)^{s_3} m_3 ]\Big]$ | no implicit leading bit in mantissa  |

## Two-level block quantization for large language models

Large language models requires significant GPU resources for inference. One way to reduce the inference resource consumption is quantization. The challenge of quantizing models is the significant accuracy degradation as the bit-width decreases. To solve this accuracy degradation, block-based number formats have been proposed. One or two levels of scaling factors are shared over a block of numbers, where the scaling factor can be exponent, exponent bias, mantissa, fixed-point number, or floating-point number. A proper blocking and sharing scheme mitigates the impact of extreme outlier values. However, block-based quantization of large language models remains to be explored, especially low bit width (1-bit/2-bit) quantization. Here we aim to explore different combinations of shared components on large language models. Specifically, we aim to estimate the hardware cost of each combination, and compare corresponding accuracy degradation given the same block size.

💡In `Facebook/OPT-350m` for language modeling, the Linear layers take up `168.02G / 174.68G x 100%=96.19%` FLOPs.

In [36]:
checkpoint = "prajjwal1/bert-tiny"
tokenizer_checkpoint = "bert-base-uncased"
dataset_name = "imdb"

## Importing the model

If you are starting from scratch, you can load the Bert checkpoint directly from HuggingFace.

In [37]:
from transformers import AutoModel

model = AutoModel.from_pretrained(checkpoint)

If you have previously ran the tutorial on Neural Architecture Search (NAS), run the following cell to import the best model obtained from the search process.

In [38]:
from pathlib import Path
import dill

with open(f"{Path.home()}/mase_hh1425/tutorial_5_best_model.pkl", "rb") as f:
    base_model = dill.load(f)

First, fetch the dataset using the `get_tokenized_dataset` utility.

In [39]:
from chop.tools import get_tokenized_dataset

dataset, tokenizer = get_tokenized_dataset(
    dataset=dataset_name,
    checkpoint=tokenizer_checkpoint,
    return_tokenizer=True,
)

INFO     Tokenizing dataset imdb with AutoTokenizer for bert-base-uncased.

## 1. Defining the Search Space

We'll start by defining a search space, i.e. enumerating the possible combinations of hyperparameters that Optuna can choose during search. We'll explore the following range of values for the model's hidden size, intermediate size, number of layers and number of heads.

In [40]:
# Seacrh space provided by leon
 
import torch
from chop.nn.quantized.modules.linear import (
    LinearInteger, # check
    LinearMinifloatDenorm, # check
    LinearMinifloatIEEE, # check
    LinearLog, # check
    LinearBlockFP, # check  
    LinearBlockMinifloat, # check
    LinearBlockLog,  # check
    LinearBinary, # check
    LinearBinaryScaling, 
    #LinearBinaryResidualSign, not supported
    LinearTernary, # check
)
 
search_space = {
    "linear_layer_choices": [
        torch.nn.Linear,
        LinearInteger, # check
        LinearMinifloatDenorm, # check
        LinearMinifloatIEEE, # check
        LinearLog, # check
        LinearBlockFP, # check
        LinearBlockMinifloat, # check
        LinearBlockLog,# check
        LinearBinary, # check
        LinearBinaryScaling, # check
        LinearTernary,
    ],
    "int_width_choices": [8, 16, 32],
    "int_frac_choices": [2, 4, 8],
    "block_size_choices": [8, 16, 32],
    "exp_size_choices": [4, 8, 16],
    "bool_choices": [True, False],
}
 
import torch
 
def get_tensor_stats(tensor):
 
    return {
 
        "mean": tensor.mean().item(),
 
        "median": tensor.median().item(),
 
        "max": tensor.max().item(),
 
    } # For any precisions needing stats

## 2. Writing a Model Constructor

We define the following function, which will get called in each iteration of the search process. The function is passed the `trial` argument, which is an Optuna object that comes with many functionalities - see the [Trial documentation](https://optuna.readthedocs.io/en/stable/reference/trial.html) for more details. Here, we use the `trial.suggest_categorical` function, which triggers the chosen sampler to choose a layer type. The suggested integer is the index into the search space for each parameter, which we defined in the previous cell.

In [41]:
from chop.tools.utils import deepsetattr
from copy import deepcopy
 
 
def construct_model(trial, set_precision = None):
 
    # Fetch the model
    trial_model = deepcopy(base_model)

 
    # Quantize layers according to optuna suggestions
    for name, layer in trial_model.named_modules():
        if isinstance(layer, torch.nn.Linear):
 
            w_stats = get_tensor_stats(layer.weight)
            b_stats = get_tensor_stats(layer.bias)
 
            if set_precision == None:
            # Per Layer Trials
                new_layer_cls = trial.suggest_categorical(
                    f"{name}_type",
                    search_space["linear_layer_choices"],
                )
            elif set_precision in search_space["linear_layer_choices"]:   
            # Global Layer Trials Per precision
                new_layer_cls = set_precision
 
            if new_layer_cls == torch.nn.Linear:
                continue
 
            kwargs = {
                "in_features": layer.in_features,
                "out_features": layer.out_features,
            }
 
            # If the chosen layer is integer, define the low precision config
            if new_layer_cls == LinearInteger:
                w = trial.suggest_categorical(f"{name}_width", search_space["int_width_choices"])
                f = trial.suggest_categorical(f"{name}_frac",  search_space["int_frac_choices"])
                kwargs["config"] = {
                    "data_in_width": w,
                    "data_in_frac_width": f,
                    "weight_width": w,
                    "weight_frac_width": f,
                    "bias_width": w,
                    "bias_frac_width": f,
                }
 
            elif new_layer_cls in [LinearMinifloatDenorm, LinearMinifloatIEEE]:
                w = trial.suggest_categorical(f"{name}_width", search_space["int_width_choices"])
                e = trial.suggest_categorical(f"{name}_exp", search_space["exp_size_choices"]) #
                kwargs["config"] = {
                    "data_in_width": w,
                    "data_in_exponent_width": e,
                    "data_in_exponent_bias": None,
                    "weight_width": w,
                    "weight_exponent_width": e,
                    "weight_exponent_bias": None,
                    "bias_width": w,
                    "bias_exponent_width": e,
                    "bias_exponent_bias": None,
                }

            elif new_layer_cls == LinearLog:
                w = trial.suggest_categorical(f"{name}_bfp_w", search_space["int_width_choices"])
                e = trial.suggest_categorical(f"{name}_bfp_e", search_space["exp_size_choices"])
 
                kwargs["config"] = {
                    "data_in_width": w, 
                    "data_in_exponent_bias": None,

                    "weight_width": w,
                    "weight_exponent_bias": None,
 
                    "bias_width": w,
                    "bias_exponent_bias": None,
                }

            elif new_layer_cls == LinearBlockFP:
                w = trial.suggest_categorical(f"{name}_bfp_w", search_space["int_width_choices"])
                bs = trial.suggest_categorical(f"{name}_bfp_bs", search_space["block_size_choices"])
                e = trial.suggest_categorical(f"{name}_bfp_e", search_space["exp_size_choices"])
 
                kwargs["config"] = {
                    "data_in_width": w, 
                    "data_in_block_size": [bs],
                    "data_in_exponent_width": e, 
                    "data_in_exponent_bias": None,
 
                    "weight_width": w, 
                    "weight_block_size": [bs],
                    "weight_exponent_width": e, 
                    "weight_exponent_bias": None,
 
                    "bias_width": w,
                    "bias_exponent_width": e,
                    "bias_exponent_bias": None,
                    "bias_block_size": [bs],
                }
 
            elif new_layer_cls == LinearBlockMinifloat:
                w = trial.suggest_categorical(f"{name}_bw", search_space["int_width_choices"])
                bs = trial.suggest_categorical(f"{name}_bs", search_space["block_size_choices"])
                e = trial.suggest_categorical(f"{name}_be", search_space["exp_size_choices"])
 
                kwargs["config"] = {
                    "data_in_width": w,
                    "data_in_block_size": [bs],
                    "data_in_exponent_width": e,
                    "data_in_exponent_bias_width": e,
 
                    "weight_width": w,
                    "weight_block_size": [bs],
                    "weight_exponent_width": e,
                    "weight_exponent_bias_width": e,
 
                    "bias_width": w,
                    "bias_exponent_width": e,
                    "bias_exponent_bias_width": e,
                    "bias_block_size": [bs],
                }
 
            elif new_layer_cls == LinearBlockLog:
                w = trial.suggest_categorical(f"{name}_bl_w", search_space["int_width_choices"])
                bs = trial.suggest_categorical(f"{name}_bl_bs", search_space["block_size_choices"])
                e = trial.suggest_categorical(f"{name}_bl_e", search_space["exp_size_choices"])
               
                kwargs["config"] = {
                    # Input
                    "data_in_width": w,
                    "data_in_block_size": [bs],
                    "data_in_exponent_bias_width": e,
 
                    # Weight
                    "weight_width": w,
                    "weight_block_size": [bs],
                    "weight_exponent_bias_width": e,
 
                    "bias_width": w,
                    "bias_exponent_bias_width": e,
                    "bias_block_size": [bs],
                }
 
            elif new_layer_cls == LinearBinary:
                is_bipolar = trial.suggest_categorical(f"{name}_bipolar", search_space["bool_choices"])
                w = trial.suggest_categorical(f"{name}_width", search_space["int_width_choices"])
                f = trial.suggest_categorical(f"{name}_frac", search_space["int_frac_choices"])
                kwargs["config"] = {
                    "weight_bipolar": is_bipolar,
                    "weight_stochastic": not is_bipolar,
                }
 
 
            elif new_layer_cls == LinearBinaryScaling:
                is_bipolar = trial.suggest_categorical(f"{name}_bipolar", search_space["bool_choices"])
                kwargs["config"] = {
                    "data_in_bipolar": is_bipolar,
                    "weight_bipolar": is_bipolar, 
                    "bias_bipolar": is_bipolar,
                    "data_in_stochastic": not is_bipolar,
                    "weight_stochastic": not is_bipolar,
                    "bias_stochastic": not is_bipolar,
                    
                    "binary_training": True,

                }
 
            elif new_layer_cls == LinearTernary:
                w = trial.suggest_categorical(f"{name}_width", search_space["int_width_choices"])
                f = trial.suggest_categorical(f"{name}_frac", search_space["int_frac_choices"])
                sf = trial.suggest_categorical(f"{name}_scaling", search_space["bool_choices"])
                kwargs["config"] = {
                    "weight_scaling_factor": sf,
                    "weight_mean": w_stats["mean"],
                    "weight_median": w_stats["median"],
                    "weight_max": w_stats["max"],
                }

            # Create the new layer (copy the weights)
            new_layer = new_layer_cls(**kwargs)
 
            new_layer.weight.data = layer.weight.data
 
            # Replace the layer in the model
            deepsetattr(trial_model, name, new_layer)
 
    return trial_model

## 3. Defining the Objective Function

Next, we define the objective function for the search, which gets called on each trial. In each trial, we create a new model instace with chosen hyperparameters according to the defined sampler. We then use the `get_trainer` utility in Mase to run a training loop on the IMDb dataset for a number of epochs. Finally, we use `evaluate` to report back the classification accuracy on the test split.

In [42]:
from chop.tools import get_trainer
import random


def objective(trial, set_precision=None):

    # Define the model
    model = construct_model(trial, set_precision=set_precision)

    trainer = get_trainer(
        model=model,
        tokenized_dataset=dataset,
        tokenizer=tokenizer,
        evaluate_metric="accuracy",
        num_train_epochs=1,
    )

    trainer.train()
    eval_results = trainer.evaluate()

    trial.set_user_attr("model", model)

    if set_precision is not None:
        precision = set_precision.__name__
    else:
        precision = "Mixed"
        
    trial.set_user_attr("model_type", precision)

    return eval_results["eval_accuracy"]

## 4. Launching the Search

Optuna provides a number of samplers, for example:

* **GridSampler**: iterates through every possible combination of hyperparameters in the search space
* **RandomSampler**: chooses a random combination of hyperparameters in each iteration
* **TPESampler**: uses Tree-structured Parzen Estimator algorithm to choose hyperparameter values.

You can define the chosen sampler by simply importing from `optuna.samplers` as below.

In [43]:
from optuna.samplers import GridSampler, RandomSampler, TPESampler

sampler = TPESampler()

With all the pieces in place, we can launch the search as follows. The number of trials is set to 1 so you can go get a coffee for 10 minutes, then proceed with the tutorial. However, this will essentially be a random model - for better results, set this to 100 and leave it running overnight!

In [44]:
import optuna


precisions_to_test = [
    LinearMinifloatIEEE, 
    LinearLog, 
    LinearBlockFP, 
    LinearBlockMinifloat, 
    LinearBlockLog,
    LinearBinary, 
    LinearBinaryScaling, 
    LinearTernary
]

for precision_type in precisions_to_test:

    precision_name = precision_type.__name__
    print(f"\n ========Starting Study for Global Precision: {precision_name}============")

    study = optuna.create_study(
        direction="maximize",
        study_name=f"bert-tiny-nas-study-{precision_name}",
        sampler=sampler,
    )

    study.optimize(
        lambda trial: objective(trial, set_precision=precision_type),
        n_trials=30,
        timeout=60 * 60 * 24,
    )

    best_acc_history = []
    current_best = 0

    for trial in study.trials:
        if trial.value > current_best:
            current_best = trial.value
        best_acc_history.append(current_best)

    print("Global best Aacc history:", best_acc_history)
    print("Best params:", study.best_params)
    print("=================================================================================")

[I 2026-02-05 02:54:04,347] A new study created in memory with name: bert-tiny-nas-study-LinearMinifloatIEEE

 ========Starting Study for Global Precision: LinearMinifloatIEEE============

/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 03:01:11,573] Trial 0 finished with value: 0.87696 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_exp': 8, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_exp': 16, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_exp': 8, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 8, 'classifier_exp': 4}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 03:08:46,966] Trial 1 finished with value: 0.87428 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_exp': 4, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_exp': 4, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 4, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 4, 'bert.encoder.layer.1.attention.output.dense_width': 8, 'bert.encoder.layer.1.attention.output.dense_exp': 4, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_exp': 16, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 32, 'classifier_exp': 8}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 03:16:06,980] Trial 2 finished with value: 0.86672 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_exp': 4, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_exp': 16, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 32, 'bert.encoder.layer.0.intermediate.dense_exp': 8, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_exp': 4, 'bert.encoder.layer.1.attention.self.key_width': 32, 'bert.encoder.layer.1.attention.self.key_exp': 16, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_exp': 16, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_exp': 8, 'classifier_width': 32, 'classifier_exp': 16}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 03:23:38,759] Trial 3 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_exp': 8, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 32, 'bert.encoder.layer.0.intermediate.dense_exp': 4, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 8, 'bert.encoder.layer.1.attention.self.key_width': 32, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 8, 'bert.encoder.layer.1.attention.output.dense_exp': 16, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_exp': 16, 'bert.encoder.layer.1.output.dense_width': 16, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 8, 'classifier_exp': 16}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 03:31:29,949] Trial 4 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_exp': 8, 'bert.encoder.layer.0.attention.self.key_width': 32, 'bert.encoder.layer.0.attention.self.key_exp': 8, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 16, 'bert.encoder.layer.0.intermediate.dense_width': 32, 'bert.encoder.layer.0.intermediate.dense_exp': 4, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 32, 'bert.encoder.layer.1.attention.self.key_exp': 4, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_exp': 8, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_exp': 8, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 16, 'classifier_exp': 16}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 03:39:15,985] Trial 5 finished with value: 0.765 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_exp': 8, 'bert.encoder.layer.0.attention.self.key_width': 32, 'bert.encoder.layer.0.attention.self.key_exp': 16, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_exp': 16, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 4, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_exp': 4, 'bert.encoder.layer.1.attention.output.dense_width': 8, 'bert.encoder.layer.1.attention.output.dense_exp': 4, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_exp': 16, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_exp': 8, 'classifier_width': 8, 'classifier_exp': 4}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 03:47:12,884] Trial 6 finished with value: 0.5316 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_exp': 8, 'bert.encoder.layer.0.attention.self.key_width': 32, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 8, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_exp': 16, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_exp': 8, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 8, 'bert.encoder.layer.1.attention.output.dense_exp': 4, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_exp': 16, 'bert.encoder.layer.1.output.dense_width': 16, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 32, 'classifier_exp': 4}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 03:54:36,834] Trial 7 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_exp': 4, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_exp': 8, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 16, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_exp': 4, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_exp': 8, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_exp': 4, 'bert.encoder.layer.1.attention.output.dense_width': 8, 'bert.encoder.layer.1.attention.output.dense_exp': 8, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_exp': 16, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_exp': 16, 'classifier_width': 8, 'classifier_exp': 8}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 04:02:02,590] Trial 8 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_exp': 8, 'bert.encoder.layer.0.attention.self.key_width': 32, 'bert.encoder.layer.0.attention.self.key_exp': 16, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 32, 'bert.encoder.layer.0.intermediate.dense_exp': 16, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_exp': 8, 'bert.encoder.layer.1.attention.self.key_width': 32, 'bert.encoder.layer.1.attention.self.key_exp': 16, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_exp': 16, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 16, 'classifier_width': 8, 'classifier_exp': 8}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 04:09:46,825] Trial 9 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_exp': 16, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_exp': 8, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_exp': 4, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_exp': 4, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_exp': 16, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 8, 'classifier_width': 16, 'classifier_exp': 16}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 04:17:22,367] Trial 10 finished with value: 0.86656 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_exp': 16, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 8, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_exp': 16, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_exp': 8, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_exp': 8, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 8, 'classifier_exp': 4}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 04:24:56,013] Trial 11 finished with value: 0.87604 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_exp': 4, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_exp': 4, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_exp': 4, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 32, 'classifier_exp': 8}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 04:32:01,786] Trial 12 finished with value: 0.87548 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_exp': 4, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_exp': 16, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_exp': 8, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 32, 'classifier_exp': 4}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 04:39:17,537] Trial 13 finished with value: 0.87536 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_exp': 4, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_exp': 4, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_exp': 4, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 32, 'classifier_exp': 8}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 04:46:26,464] Trial 14 finished with value: 0.87516 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_exp': 16, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_exp': 16, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_exp': 8, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_exp': 4, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 16, 'classifier_exp': 8}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 04:54:09,486] Trial 15 finished with value: 0.87588 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_exp': 8, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_exp': 8, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 8, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_exp': 4, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_exp': 8, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 16, 'classifier_width': 8, 'classifier_exp': 4}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 05:01:19,845] Trial 16 finished with value: 0.87668 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_exp': 4, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_exp': 16, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_exp': 8, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 32, 'classifier_exp': 4}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 05:08:26,350] Trial 17 finished with value: 0.8694 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_exp': 8, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_exp': 16, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 16, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_exp': 8, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_exp': 8, 'bert.encoder.layer.1.output.dense_width': 16, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 32, 'classifier_exp': 4}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 05:15:38,455] Trial 18 finished with value: 0.50992 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_exp': 4, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_exp': 16, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_exp': 16, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_exp': 16, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_exp': 8, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 16, 'classifier_width': 8, 'classifier_exp': 4}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 05:23:00,154] Trial 19 finished with value: 0.87356 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_exp': 16, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_exp': 8, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_exp': 8, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_exp': 16, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_exp': 8, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 8, 'classifier_width': 16, 'classifier_exp': 4}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 05:30:14,510] Trial 20 finished with value: 0.86912 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_exp': 4, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_exp': 16, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 16, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_exp': 8, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_exp': 8, 'bert.encoder.layer.1.output.dense_width': 16, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 32, 'classifier_exp': 4}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 05:37:30,596] Trial 21 finished with value: 0.87528 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_exp': 4, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_exp': 16, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_exp': 4, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 32, 'classifier_exp': 8}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 05:44:37,527] Trial 22 finished with value: 0.87384 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_exp': 4, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_exp': 4, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_exp': 8, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 32, 'classifier_exp': 4}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 05:52:09,643] Trial 23 finished with value: 0.87692 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_exp': 4, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_exp': 8, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_exp': 4, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 32, 'classifier_exp': 8}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 05:59:32,057] Trial 24 finished with value: 0.87672 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_exp': 4, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_exp': 8, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_exp': 8, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 32, 'classifier_exp': 4}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 06:07:19,231] Trial 25 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_exp': 8, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_exp': 8, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_exp': 4, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 8, 'classifier_exp': 8}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 06:14:39,324] Trial 26 finished with value: 0.8766 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_exp': 4, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_exp': 8, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_exp': 8, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 32, 'classifier_exp': 4}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 06:21:38,789] Trial 27 finished with value: 0.87504 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_exp': 4, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_exp': 8, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_exp': 8, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 32, 'classifier_exp': 4}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 06:28:43,938] Trial 28 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_exp': 16, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_exp': 8, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_exp': 16, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_exp': 8, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_exp': 8, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_exp': 16, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_exp': 16, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 8, 'classifier_width': 16, 'classifier_exp': 16}. Best is trial 0 with value: 0.87696.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 06:36:00,410] Trial 29 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_exp': 8, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_exp': 16, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_exp': 8, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_exp': 8, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_exp': 4, 'bert.encoder.layer.1.attention.self.key_width': 32, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_exp': 4, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_exp': 8, 'bert.encoder.layer.1.output.dense_width': 16, 'bert.encoder.layer.1.output.dense_exp': 16, 'classifier_width': 8, 'classifier_exp': 8}. Best is trial 0 with value: 0.87696.
[I 2026-02-05 06:36:00,626] A new study created in memory with name: bert-tiny-nas-study-LinearLog

Global best Aacc history: [0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696, 0.87696]
Best params: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_exp': 8, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_exp': 4, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_exp': 4, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_exp': 16, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_exp': 16, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_exp': 8, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_exp': 8, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_exp': 4, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_exp': 4, 'classifier_width': 8, 'classifier_exp': 4}
=================================================================================

 ========Starting Study for Global Precision: LinearLog============

/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 06:38:16,333] Trial 0 finished with value: 0.87264 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 32, 'bert.encoder.layer.0.attention.self.query_bfp_e': 8, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_e': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 8, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 8, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 16, 'classifier_bfp_e': 4}. Best is trial 0 with value: 0.87264.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 06:40:36,426] Trial 1 finished with value: 0.87404 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 32, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_e': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.1.output.dense_bfp_w': 16, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 8, 'classifier_bfp_e': 8}. Best is trial 1 with value: 0.87404.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 06:42:54,592] Trial 2 finished with value: 0.87392 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 32, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 8, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 4, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 8, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 32, 'classifier_bfp_e': 4}. Best is trial 1 with value: 0.87404.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 06:45:14,520] Trial 3 finished with value: 0.87396 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 8, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_e': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.0.output.dense_bfp_w': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 8, 'bert.encoder.layer.1.attention.self.key_bfp_w': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 4, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 16, 'bert.encoder.layer.1.output.dense_bfp_e': 8, 'classifier_bfp_w': 16, 'classifier_bfp_e': 8}. Best is trial 1 with value: 0.87404.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 06:47:31,631] Trial 4 finished with value: 0.87384 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 32, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_e': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.0.output.dense_bfp_w': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 16, 'bert.encoder.layer.1.output.dense_bfp_e': 8, 'classifier_bfp_w': 16, 'classifier_bfp_e': 16}. Best is trial 1 with value: 0.87404.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 06:49:45,246] Trial 5 finished with value: 0.87416 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.0.output.dense_bfp_w': 16, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 4, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 8, 'classifier_bfp_w': 32, 'classifier_bfp_e': 4}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 06:51:58,843] Trial 6 finished with value: 0.87156 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_e': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 8, 'classifier_bfp_w': 32, 'classifier_bfp_e': 4}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 06:54:16,994] Trial 7 finished with value: 0.87264 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 8, 'bert.encoder.layer.0.attention.self.query_bfp_e': 8, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 16, 'bert.encoder.layer.1.output.dense_bfp_e': 8, 'classifier_bfp_w': 32, 'classifier_bfp_e': 16}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 06:56:27,024] Trial 8 finished with value: 0.87388 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 8, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_e': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 8, 'bert.encoder.layer.1.output.dense_bfp_e': 8, 'classifier_bfp_w': 16, 'classifier_bfp_e': 4}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 06:58:39,155] Trial 9 finished with value: 0.87156 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 8, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 4, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 16, 'classifier_bfp_e': 8}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:01:06,168] Trial 10 finished with value: 0.87296 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.0.output.dense_bfp_w': 16, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 4, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 16, 'classifier_bfp_w': 32, 'classifier_bfp_e': 4}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:03:24,584] Trial 11 finished with value: 0.87072 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.0.output.dense_bfp_w': 16, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.1.output.dense_bfp_w': 16, 'bert.encoder.layer.1.output.dense_bfp_e': 16, 'classifier_bfp_w': 8, 'classifier_bfp_e': 8}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:05:42,586] Trial 12 finished with value: 0.87216 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 32, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.0.output.dense_bfp_w': 16, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 4, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 8, 'classifier_bfp_e': 8}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:08:00,837] Trial 13 finished with value: 0.87268 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 32, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.0.output.dense_bfp_w': 16, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.1.output.dense_bfp_w': 16, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 8, 'classifier_bfp_e': 8}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:10:20,487] Trial 14 finished with value: 0.87412 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 16, 'classifier_bfp_w': 8, 'classifier_bfp_e': 16}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:12:42,016] Trial 15 finished with value: 0.87276 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 16, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 16, 'classifier_bfp_w': 32, 'classifier_bfp_e': 16}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:14:52,587] Trial 16 finished with value: 0.87344 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 16, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 16, 'classifier_bfp_w': 8, 'classifier_bfp_e': 16}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:17:10,107] Trial 17 finished with value: 0.873 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 16, 'classifier_bfp_w': 32, 'classifier_bfp_e': 16}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:19:27,197] Trial 18 finished with value: 0.87208 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_e': 4, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 8, 'classifier_bfp_w': 8, 'classifier_bfp_e': 4}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:21:44,538] Trial 19 finished with value: 0.87208 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 16, 'bert.encoder.layer.0.output.dense_bfp_e': 8, 'bert.encoder.layer.1.attention.self.key_bfp_w': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 16, 'classifier_bfp_w': 32, 'classifier_bfp_e': 16}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:23:58,386] Trial 20 finished with value: 0.87272 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 16, 'classifier_bfp_w': 8, 'classifier_bfp_e': 16}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:26:15,337] Trial 21 finished with value: 0.87108 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 32, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_e': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.1.output.dense_bfp_w': 16, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 8, 'classifier_bfp_e': 8}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:28:37,750] Trial 22 finished with value: 0.871 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 32, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_e': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.1.output.dense_bfp_w': 16, 'bert.encoder.layer.1.output.dense_bfp_e': 8, 'classifier_bfp_w': 8, 'classifier_bfp_e': 4}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:30:53,242] Trial 23 finished with value: 0.87164 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 8, 'bert.encoder.layer.0.attention.self.query_bfp_e': 8, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 4, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.1.output.dense_bfp_w': 8, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 8, 'classifier_bfp_e': 8}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:33:18,947] Trial 24 finished with value: 0.86952 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 4, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 8, 'classifier_bfp_e': 4}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:35:35,214] Trial 25 finished with value: 0.87076 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 32, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 16, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.1.output.dense_bfp_w': 16, 'bert.encoder.layer.1.output.dense_bfp_e': 16, 'classifier_bfp_w': 8, 'classifier_bfp_e': 8}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:37:51,559] Trial 26 finished with value: 0.87164 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 8, 'classifier_bfp_w': 32, 'classifier_bfp_e': 16}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:40:05,817] Trial 27 finished with value: 0.8698 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 8, 'classifier_bfp_w': 8, 'classifier_bfp_e': 16}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:42:18,871] Trial 28 finished with value: 0.8722 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 8, 'bert.encoder.layer.0.attention.self.query_bfp_e': 8, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 8, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_e': 4, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 8, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 8, 'classifier_bfp_e': 8}. Best is trial 5 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:44:49,187] Trial 29 finished with value: 0.87176 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 32, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.0.output.dense_bfp_w': 16, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.1.output.dense_bfp_w': 16, 'bert.encoder.layer.1.output.dense_bfp_e': 16, 'classifier_bfp_w': 32, 'classifier_bfp_e': 4}. Best is trial 5 with value: 0.87416.
[I 2026-02-05 07:44:49,363] A new study created in memory with name: bert-tiny-nas-study-LinearBlockFP

Global best Aacc history: [0.87264, 0.87404, 0.87404, 0.87404, 0.87404, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416]
Best params: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.0.output.dense_bfp_w': 16, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 4, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 8, 'classifier_bfp_w': 32, 'classifier_bfp_e': 4}
=================================================================================

 ========Starting Study for Global Precision: LinearBlockFP============

/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 07:57:49,572] Trial 0 finished with value: 0.8752 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 8, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.0.output.dense_bfp_w': 32, 'bert.encoder.layer.0.output.dense_bfp_bs': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 8, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.1.output.dense_bfp_w': 16, 'bert.encoder.layer.1.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 16, 'classifier_bfp_bs': 8, 'classifier_bfp_e': 4}. Best is trial 0 with value: 0.8752.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 08:11:00,292] Trial 1 finished with value: 0.87572 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 32, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 16, 'classifier_bfp_bs': 32, 'classifier_bfp_e': 8}. Best is trial 1 with value: 0.87572.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 08:23:04,732] Trial 2 finished with value: 0.87432 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 32, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 32, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.0.output.dense_bfp_w': 32, 'bert.encoder.layer.0.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 8, 'bert.encoder.layer.1.attention.self.key_bfp_e': 4, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 8, 'bert.encoder.layer.1.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 32, 'classifier_bfp_bs': 32, 'classifier_bfp_e': 8}. Best is trial 1 with value: 0.87572.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 08:34:29,586] Trial 3 finished with value: 0.87444 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 8, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 8, 'bert.encoder.layer.0.attention.self.query_bfp_e': 8, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 8, 'bert.encoder.layer.0.attention.self.key_bfp_e': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 32, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 8, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.1.output.dense_bfp_w': 16, 'bert.encoder.layer.1.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.output.dense_bfp_e': 16, 'classifier_bfp_w': 16, 'classifier_bfp_bs': 16, 'classifier_bfp_e': 8}. Best is trial 1 with value: 0.87572.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 08:46:21,426] Trial 4 finished with value: 0.87588 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 8, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 8, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 8, 'bert.encoder.layer.1.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 32, 'classifier_bfp_bs': 8, 'classifier_bfp_e': 16}. Best is trial 4 with value: 0.87588.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 08:57:37,054] Trial 5 finished with value: 0.87416 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 8, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 8, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 32, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 8, 'bert.encoder.layer.1.attention.self.key_bfp_e': 4, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 8, 'bert.encoder.layer.1.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.output.dense_bfp_e': 8, 'classifier_bfp_w': 16, 'classifier_bfp_bs': 8, 'classifier_bfp_e': 16}. Best is trial 4 with value: 0.87588.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 09:09:48,329] Trial 6 finished with value: 0.87204 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 32, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 32, 'bert.encoder.layer.0.attention.self.query_bfp_e': 8, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.output.dense_bfp_e': 8, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 8, 'bert.encoder.layer.1.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.output.dense_bfp_e': 16, 'classifier_bfp_w': 32, 'classifier_bfp_bs': 32, 'classifier_bfp_e': 8}. Best is trial 4 with value: 0.87588.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 09:21:28,398] Trial 7 finished with value: 0.8748 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 8, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 8, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.0.output.dense_bfp_w': 16, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 8, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.1.output.dense_bfp_w': 8, 'bert.encoder.layer.1.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 8, 'classifier_bfp_bs': 32, 'classifier_bfp_e': 4}. Best is trial 4 with value: 0.87588.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 09:33:37,456] Trial 8 finished with value: 0.87392 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 32, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 8, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 16, 'bert.encoder.layer.0.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.output.dense_bfp_e': 8, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 4, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 16, 'bert.encoder.layer.1.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.output.dense_bfp_e': 16, 'classifier_bfp_w': 32, 'classifier_bfp_bs': 32, 'classifier_bfp_e': 8}. Best is trial 4 with value: 0.87588.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 09:44:56,869] Trial 9 finished with value: 0.87248 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 8, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 8, 'bert.encoder.layer.0.attention.self.query_bfp_e': 8, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 8, 'bert.encoder.layer.0.attention.self.key_bfp_e': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 32, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 8, 'bert.encoder.layer.1.attention.self.key_bfp_e': 4, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.output.dense_bfp_e': 16, 'classifier_bfp_w': 32, 'classifier_bfp_bs': 32, 'classifier_bfp_e': 8}. Best is trial 4 with value: 0.87588.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 09:56:44,590] Trial 10 finished with value: 0.87368 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 8, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_bs': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 8, 'bert.encoder.layer.1.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.output.dense_bfp_e': 8, 'classifier_bfp_w': 8, 'classifier_bfp_bs': 8, 'classifier_bfp_e': 16}. Best is trial 4 with value: 0.87588.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 10:09:44,920] Trial 11 finished with value: 0.87504 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 32, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 16, 'classifier_bfp_bs': 16, 'classifier_bfp_e': 16}. Best is trial 4 with value: 0.87588.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 10:22:58,167] Trial 12 finished with value: 0.8764 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 32, 'classifier_bfp_bs': 8, 'classifier_bfp_e': 16}. Best is trial 12 with value: 0.8764.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 10:36:02,296] Trial 13 finished with value: 0.87416 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 32, 'classifier_bfp_bs': 8, 'classifier_bfp_e': 16}. Best is trial 12 with value: 0.8764.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 10:49:34,813] Trial 14 finished with value: 0.8744 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 32, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 32, 'classifier_bfp_bs': 8, 'classifier_bfp_e': 16}. Best is trial 12 with value: 0.8764.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 11:01:41,313] Trial 15 finished with value: 0.87532 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 8, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 8, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 8, 'bert.encoder.layer.1.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 32, 'classifier_bfp_bs': 8, 'classifier_bfp_e': 16}. Best is trial 12 with value: 0.8764.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 11:14:02,768] Trial 16 finished with value: 0.8752 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 32, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_bs': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.output.dense_bfp_e': 8, 'classifier_bfp_w': 32, 'classifier_bfp_bs': 8, 'classifier_bfp_e': 16}. Best is trial 12 with value: 0.8764.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 11:26:51,307] Trial 17 finished with value: 0.87432 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 8, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 8, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 16, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 8, 'classifier_bfp_bs': 8, 'classifier_bfp_e': 16}. Best is trial 12 with value: 0.8764.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 11:39:07,293] Trial 18 finished with value: 0.87536 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 8, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 8, 'bert.encoder.layer.1.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 32, 'classifier_bfp_bs': 16, 'classifier_bfp_e': 4}. Best is trial 12 with value: 0.8764.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 11:50:49,048] Trial 19 finished with value: 0.87356 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 32, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 32, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_bs': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 8, 'bert.encoder.layer.1.attention.self.key_bfp_w': 32, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 16, 'bert.encoder.layer.1.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.output.dense_bfp_e': 8, 'classifier_bfp_w': 32, 'classifier_bfp_bs': 8, 'classifier_bfp_e': 16}. Best is trial 12 with value: 0.8764.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 12:04:28,870] Trial 20 finished with value: 0.87388 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 8, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 16, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 8, 'classifier_bfp_bs': 8, 'classifier_bfp_e': 16}. Best is trial 12 with value: 0.8764.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 12:17:56,800] Trial 21 finished with value: 0.87384 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 32, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 16, 'classifier_bfp_bs': 32, 'classifier_bfp_e': 8}. Best is trial 12 with value: 0.8764.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 12:31:24,913] Trial 22 finished with value: 0.87452 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 32, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 16, 'classifier_bfp_bs': 32, 'classifier_bfp_e': 8}. Best is trial 12 with value: 0.8764.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 12:44:20,654] Trial 23 finished with value: 0.87316 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 8, 'bert.encoder.layer.0.attention.self.key_bfp_e': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 32, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 16, 'classifier_bfp_bs': 16, 'classifier_bfp_e': 4}. Best is trial 12 with value: 0.8764.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 12:57:53,722] Trial 24 finished with value: 0.87416 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 32, 'classifier_bfp_bs': 8, 'classifier_bfp_e': 16}. Best is trial 12 with value: 0.8764.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 13:10:15,871] Trial 25 finished with value: 0.87304 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 8, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 32, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 8, 'bert.encoder.layer.1.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 16, 'classifier_bfp_bs': 32, 'classifier_bfp_e': 8}. Best is trial 12 with value: 0.8764.
WARNING:evaluate.loading:Using the latest cached version of the module from /home/testunot/.cache/huggingface/modules/evaluate_modules/metrics/evaluate-metric--accuracy/f887c0aab52c2d38e1f8a215681126379eca617f96c447638f751434e8e65b14 (last modified on Wed Jan 21 17:36:38 2026) since it couldn't be found locally at evaluate-metric--accuracy, or remotely on the Hugging Face Hub.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 13:23:44,861] Trial 26 finished with value: 0.8736 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 32, 'classifier_bfp_bs': 8, 'classifier_bfp_e': 16}. Best is trial 12 with value: 0.8764.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 13:36:45,139] Trial 27 finished with value: 0.87264 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 8, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 32, 'classifier_bfp_bs': 8, 'classifier_bfp_e': 16}. Best is trial 12 with value: 0.8764.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 13:48:05,244] Trial 28 finished with value: 0.87504 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 32, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 8, 'bert.encoder.layer.0.attention.self.query_bfp_e': 16, 'bert.encoder.layer.0.attention.self.key_bfp_w': 32, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.0.output.dense_bfp_w': 16, 'bert.encoder.layer.0.output.dense_bfp_bs': 8, 'bert.encoder.layer.0.output.dense_bfp_e': 8, 'bert.encoder.layer.1.attention.self.key_bfp_w': 32, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.1.attention.self.key_bfp_e': 4, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 4, 'bert.encoder.layer.1.output.dense_bfp_w': 16, 'bert.encoder.layer.1.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.output.dense_bfp_e': 16, 'classifier_bfp_w': 8, 'classifier_bfp_bs': 16, 'classifier_bfp_e': 4}. Best is trial 12 with value: 0.8764.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 13:59:39,476] Trial 29 finished with value: 0.87444 and parameters: {'bert.encoder.layer.0.attention.self.query_bfp_w': 8, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 32, 'bert.encoder.layer.0.attention.self.query_bfp_e': 8, 'bert.encoder.layer.0.attention.self.key_bfp_w': 8, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.0.attention.self.key_bfp_e': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 32, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 4, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 16, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.0.output.dense_bfp_w': 32, 'bert.encoder.layer.0.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.output.dense_bfp_e': 4, 'bert.encoder.layer.1.attention.self.key_bfp_w': 16, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.1.output.dense_bfp_w': 8, 'bert.encoder.layer.1.output.dense_bfp_bs': 8, 'bert.encoder.layer.1.output.dense_bfp_e': 8, 'classifier_bfp_w': 16, 'classifier_bfp_bs': 32, 'classifier_bfp_e': 8}. Best is trial 12 with value: 0.8764.
[I 2026-02-05 13:59:39,712] A new study created in memory with name: bert-tiny-nas-study-LinearBlockMinifloat

Global best Aacc history: [0.8752, 0.87572, 0.87572, 0.87572, 0.87588, 0.87588, 0.87588, 0.87588, 0.87588, 0.87588, 0.87588, 0.87588, 0.8764, 0.8764, 0.8764, 0.8764, 0.8764, 0.8764, 0.8764, 0.8764, 0.8764, 0.8764, 0.8764, 0.8764, 0.8764, 0.8764, 0.8764, 0.8764, 0.8764, 0.8764]
Best params: {'bert.encoder.layer.0.attention.self.query_bfp_w': 16, 'bert.encoder.layer.0.attention.self.query_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.query_bfp_e': 4, 'bert.encoder.layer.0.attention.self.key_bfp_w': 16, 'bert.encoder.layer.0.attention.self.key_bfp_bs': 16, 'bert.encoder.layer.0.attention.self.key_bfp_e': 4, 'bert.encoder.layer.0.attention.output.dense_bfp_w': 8, 'bert.encoder.layer.0.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bfp_e': 8, 'bert.encoder.layer.0.intermediate.dense_bfp_w': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bfp_e': 8, 'bert.encoder.layer.0.output.dense_bfp_w': 8, 'bert.encoder.layer.0.output.dense_bfp_bs': 32, 'bert.encoder.layer.0.output.dense_bfp_e': 16, 'bert.encoder.layer.1.attention.self.key_bfp_w': 8, 'bert.encoder.layer.1.attention.self.key_bfp_bs': 32, 'bert.encoder.layer.1.attention.self.key_bfp_e': 8, 'bert.encoder.layer.1.attention.output.dense_bfp_w': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bfp_e': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_w': 16, 'bert.encoder.layer.1.intermediate.dense_bfp_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bfp_e': 16, 'bert.encoder.layer.1.output.dense_bfp_w': 32, 'bert.encoder.layer.1.output.dense_bfp_bs': 32, 'bert.encoder.layer.1.output.dense_bfp_e': 4, 'classifier_bfp_w': 32, 'classifier_bfp_bs': 8, 'classifier_bfp_e': 16}
=================================================================================

 ========Starting Study for Global Precision: LinearBlockMinifloat============

/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 14:14:45,602] Trial 0 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 32, 'bert.encoder.layer.0.attention.self.query_be': 16, 'bert.encoder.layer.0.attention.self.key_bw': 8, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 4, 'bert.encoder.layer.0.attention.output.dense_bw': 8, 'bert.encoder.layer.0.attention.output.dense_bs': 16, 'bert.encoder.layer.0.attention.output.dense_be': 16, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 16, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 32, 'bert.encoder.layer.0.output.dense_bs': 8, 'bert.encoder.layer.0.output.dense_be': 16, 'bert.encoder.layer.1.attention.self.key_bw': 8, 'bert.encoder.layer.1.attention.self.key_bs': 32, 'bert.encoder.layer.1.attention.self.key_be': 16, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 32, 'bert.encoder.layer.1.attention.output.dense_be': 16, 'bert.encoder.layer.1.intermediate.dense_bw': 8, 'bert.encoder.layer.1.intermediate.dense_bs': 16, 'bert.encoder.layer.1.intermediate.dense_be': 16, 'bert.encoder.layer.1.output.dense_bw': 32, 'bert.encoder.layer.1.output.dense_bs': 32, 'bert.encoder.layer.1.output.dense_be': 8, 'classifier_bw': 16, 'classifier_bs': 8, 'classifier_be': 16}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 14:30:32,466] Trial 1 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 8, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 8, 'bert.encoder.layer.0.attention.self.key_bs': 8, 'bert.encoder.layer.0.attention.self.key_be': 8, 'bert.encoder.layer.0.attention.output.dense_bw': 8, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 16, 'bert.encoder.layer.0.intermediate.dense_bs': 8, 'bert.encoder.layer.0.intermediate.dense_be': 16, 'bert.encoder.layer.0.output.dense_bw': 8, 'bert.encoder.layer.0.output.dense_bs': 16, 'bert.encoder.layer.0.output.dense_be': 16, 'bert.encoder.layer.1.attention.self.key_bw': 32, 'bert.encoder.layer.1.attention.self.key_bs': 32, 'bert.encoder.layer.1.attention.self.key_be': 4, 'bert.encoder.layer.1.attention.output.dense_bw': 8, 'bert.encoder.layer.1.attention.output.dense_bs': 16, 'bert.encoder.layer.1.attention.output.dense_be': 8, 'bert.encoder.layer.1.intermediate.dense_bw': 32, 'bert.encoder.layer.1.intermediate.dense_bs': 16, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 32, 'bert.encoder.layer.1.output.dense_bs': 32, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 8, 'classifier_bs': 8, 'classifier_be': 8}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 14:45:46,703] Trial 2 finished with value: 0.84824 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 32, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 8, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 16, 'bert.encoder.layer.0.attention.output.dense_bw': 32, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 16, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 32, 'bert.encoder.layer.0.output.dense_bs': 8, 'bert.encoder.layer.0.output.dense_be': 16, 'bert.encoder.layer.1.attention.self.key_bw': 16, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 32, 'bert.encoder.layer.1.attention.output.dense_be': 8, 'bert.encoder.layer.1.intermediate.dense_bw': 32, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 8, 'bert.encoder.layer.1.output.dense_bs': 8, 'bert.encoder.layer.1.output.dense_be': 4, 'classifier_bw': 32, 'classifier_bs': 8, 'classifier_be': 4}. Best is trial 2 with value: 0.84824.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 14:59:35,996] Trial 3 finished with value: 0.66224 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 8, 'bert.encoder.layer.0.attention.self.query_bs': 8, 'bert.encoder.layer.0.attention.self.query_be': 16, 'bert.encoder.layer.0.attention.self.key_bw': 32, 'bert.encoder.layer.0.attention.self.key_bs': 16, 'bert.encoder.layer.0.attention.self.key_be': 16, 'bert.encoder.layer.0.attention.output.dense_bw': 32, 'bert.encoder.layer.0.attention.output.dense_bs': 8, 'bert.encoder.layer.0.attention.output.dense_be': 4, 'bert.encoder.layer.0.intermediate.dense_bw': 16, 'bert.encoder.layer.0.intermediate.dense_bs': 32, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 8, 'bert.encoder.layer.0.output.dense_bs': 16, 'bert.encoder.layer.0.output.dense_be': 16, 'bert.encoder.layer.1.attention.self.key_bw': 8, 'bert.encoder.layer.1.attention.self.key_bs': 32, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 16, 'bert.encoder.layer.1.attention.output.dense_bs': 16, 'bert.encoder.layer.1.attention.output.dense_be': 8, 'bert.encoder.layer.1.intermediate.dense_bw': 16, 'bert.encoder.layer.1.intermediate.dense_bs': 8, 'bert.encoder.layer.1.intermediate.dense_be': 16, 'bert.encoder.layer.1.output.dense_bw': 8, 'bert.encoder.layer.1.output.dense_bs': 8, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 16, 'classifier_bs': 16, 'classifier_be': 8}. Best is trial 2 with value: 0.84824.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 15:12:51,921] Trial 4 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 8, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 16, 'bert.encoder.layer.0.attention.self.key_bw': 8, 'bert.encoder.layer.0.attention.self.key_bs': 16, 'bert.encoder.layer.0.attention.self.key_be': 8, 'bert.encoder.layer.0.attention.output.dense_bw': 8, 'bert.encoder.layer.0.attention.output.dense_bs': 16, 'bert.encoder.layer.0.attention.output.dense_be': 4, 'bert.encoder.layer.0.intermediate.dense_bw': 16, 'bert.encoder.layer.0.intermediate.dense_bs': 8, 'bert.encoder.layer.0.intermediate.dense_be': 16, 'bert.encoder.layer.0.output.dense_bw': 8, 'bert.encoder.layer.0.output.dense_bs': 8, 'bert.encoder.layer.0.output.dense_be': 4, 'bert.encoder.layer.1.attention.self.key_bw': 16, 'bert.encoder.layer.1.attention.self.key_bs': 16, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 16, 'bert.encoder.layer.1.attention.output.dense_be': 4, 'bert.encoder.layer.1.intermediate.dense_bw': 32, 'bert.encoder.layer.1.intermediate.dense_bs': 16, 'bert.encoder.layer.1.intermediate.dense_be': 16, 'bert.encoder.layer.1.output.dense_bw': 16, 'bert.encoder.layer.1.output.dense_bs': 8, 'bert.encoder.layer.1.output.dense_be': 4, 'classifier_bw': 16, 'classifier_bs': 8, 'classifier_be': 16}. Best is trial 2 with value: 0.84824.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 15:25:54,958] Trial 5 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 16, 'bert.encoder.layer.0.attention.self.query_bs': 8, 'bert.encoder.layer.0.attention.self.query_be': 16, 'bert.encoder.layer.0.attention.self.key_bw': 32, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 8, 'bert.encoder.layer.0.attention.output.dense_bw': 8, 'bert.encoder.layer.0.attention.output.dense_bs': 16, 'bert.encoder.layer.0.attention.output.dense_be': 16, 'bert.encoder.layer.0.intermediate.dense_bw': 16, 'bert.encoder.layer.0.intermediate.dense_bs': 8, 'bert.encoder.layer.0.intermediate.dense_be': 4, 'bert.encoder.layer.0.output.dense_bw': 32, 'bert.encoder.layer.0.output.dense_bs': 8, 'bert.encoder.layer.0.output.dense_be': 4, 'bert.encoder.layer.1.attention.self.key_bw': 8, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 4, 'bert.encoder.layer.1.attention.output.dense_bw': 16, 'bert.encoder.layer.1.attention.output.dense_bs': 8, 'bert.encoder.layer.1.attention.output.dense_be': 16, 'bert.encoder.layer.1.intermediate.dense_bw': 32, 'bert.encoder.layer.1.intermediate.dense_bs': 8, 'bert.encoder.layer.1.intermediate.dense_be': 8, 'bert.encoder.layer.1.output.dense_bw': 8, 'bert.encoder.layer.1.output.dense_bs': 16, 'bert.encoder.layer.1.output.dense_be': 4, 'classifier_bw': 8, 'classifier_bs': 8, 'classifier_be': 4}. Best is trial 2 with value: 0.84824.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 15:40:31,477] Trial 6 finished with value: 0.70412 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 16, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 8, 'bert.encoder.layer.0.attention.self.key_bs': 8, 'bert.encoder.layer.0.attention.self.key_be': 16, 'bert.encoder.layer.0.attention.output.dense_bw': 32, 'bert.encoder.layer.0.attention.output.dense_bs': 8, 'bert.encoder.layer.0.attention.output.dense_be': 16, 'bert.encoder.layer.0.intermediate.dense_bw': 8, 'bert.encoder.layer.0.intermediate.dense_bs': 16, 'bert.encoder.layer.0.intermediate.dense_be': 16, 'bert.encoder.layer.0.output.dense_bw': 32, 'bert.encoder.layer.0.output.dense_bs': 16, 'bert.encoder.layer.0.output.dense_be': 16, 'bert.encoder.layer.1.attention.self.key_bw': 16, 'bert.encoder.layer.1.attention.self.key_bs': 32, 'bert.encoder.layer.1.attention.self.key_be': 4, 'bert.encoder.layer.1.attention.output.dense_bw': 8, 'bert.encoder.layer.1.attention.output.dense_bs': 32, 'bert.encoder.layer.1.attention.output.dense_be': 8, 'bert.encoder.layer.1.intermediate.dense_bw': 32, 'bert.encoder.layer.1.intermediate.dense_bs': 16, 'bert.encoder.layer.1.intermediate.dense_be': 16, 'bert.encoder.layer.1.output.dense_bw': 16, 'bert.encoder.layer.1.output.dense_bs': 8, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 16, 'classifier_bs': 32, 'classifier_be': 16}. Best is trial 2 with value: 0.84824.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 15:56:28,408] Trial 7 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 32, 'bert.encoder.layer.0.attention.self.query_be': 4, 'bert.encoder.layer.0.attention.self.key_bw': 16, 'bert.encoder.layer.0.attention.self.key_bs': 16, 'bert.encoder.layer.0.attention.self.key_be': 8, 'bert.encoder.layer.0.attention.output.dense_bw': 8, 'bert.encoder.layer.0.attention.output.dense_bs': 8, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 32, 'bert.encoder.layer.0.intermediate.dense_be': 4, 'bert.encoder.layer.0.output.dense_bw': 16, 'bert.encoder.layer.0.output.dense_bs': 32, 'bert.encoder.layer.0.output.dense_be': 4, 'bert.encoder.layer.1.attention.self.key_bw': 8, 'bert.encoder.layer.1.attention.self.key_bs': 32, 'bert.encoder.layer.1.attention.self.key_be': 4, 'bert.encoder.layer.1.attention.output.dense_bw': 16, 'bert.encoder.layer.1.attention.output.dense_bs': 8, 'bert.encoder.layer.1.attention.output.dense_be': 4, 'bert.encoder.layer.1.intermediate.dense_bw': 8, 'bert.encoder.layer.1.intermediate.dense_bs': 8, 'bert.encoder.layer.1.intermediate.dense_be': 16, 'bert.encoder.layer.1.output.dense_bw': 8, 'bert.encoder.layer.1.output.dense_bs': 8, 'bert.encoder.layer.1.output.dense_be': 4, 'classifier_bw': 8, 'classifier_bs': 32, 'classifier_be': 4}. Best is trial 2 with value: 0.84824.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 16:10:04,110] Trial 8 finished with value: 0.52848 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 8, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 4, 'bert.encoder.layer.0.attention.self.key_bw': 16, 'bert.encoder.layer.0.attention.self.key_bs': 8, 'bert.encoder.layer.0.attention.self.key_be': 16, 'bert.encoder.layer.0.attention.output.dense_bw': 32, 'bert.encoder.layer.0.attention.output.dense_bs': 16, 'bert.encoder.layer.0.attention.output.dense_be': 16, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 16, 'bert.encoder.layer.0.intermediate.dense_be': 16, 'bert.encoder.layer.0.output.dense_bw': 32, 'bert.encoder.layer.0.output.dense_bs': 8, 'bert.encoder.layer.0.output.dense_be': 16, 'bert.encoder.layer.1.attention.self.key_bw': 32, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 4, 'bert.encoder.layer.1.attention.output.dense_bw': 16, 'bert.encoder.layer.1.attention.output.dense_bs': 16, 'bert.encoder.layer.1.attention.output.dense_be': 16, 'bert.encoder.layer.1.intermediate.dense_bw': 16, 'bert.encoder.layer.1.intermediate.dense_bs': 8, 'bert.encoder.layer.1.intermediate.dense_be': 8, 'bert.encoder.layer.1.output.dense_bw': 32, 'bert.encoder.layer.1.output.dense_bs': 32, 'bert.encoder.layer.1.output.dense_be': 4, 'classifier_bw': 32, 'classifier_bs': 16, 'classifier_be': 16}. Best is trial 2 with value: 0.84824.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 16:25:03,025] Trial 9 finished with value: 0.56388 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 16, 'bert.encoder.layer.0.attention.self.query_bs': 32, 'bert.encoder.layer.0.attention.self.query_be': 4, 'bert.encoder.layer.0.attention.self.key_bw': 8, 'bert.encoder.layer.0.attention.self.key_bs': 8, 'bert.encoder.layer.0.attention.self.key_be': 8, 'bert.encoder.layer.0.attention.output.dense_bw': 32, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 4, 'bert.encoder.layer.0.intermediate.dense_bw': 8, 'bert.encoder.layer.0.intermediate.dense_bs': 32, 'bert.encoder.layer.0.intermediate.dense_be': 16, 'bert.encoder.layer.0.output.dense_bw': 16, 'bert.encoder.layer.0.output.dense_bs': 32, 'bert.encoder.layer.0.output.dense_be': 4, 'bert.encoder.layer.1.attention.self.key_bw': 16, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 8, 'bert.encoder.layer.1.attention.output.dense_bs': 16, 'bert.encoder.layer.1.attention.output.dense_be': 16, 'bert.encoder.layer.1.intermediate.dense_bw': 8, 'bert.encoder.layer.1.intermediate.dense_bs': 16, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 32, 'bert.encoder.layer.1.output.dense_bs': 16, 'bert.encoder.layer.1.output.dense_be': 4, 'classifier_bw': 32, 'classifier_bs': 8, 'classifier_be': 8}. Best is trial 2 with value: 0.84824.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 16:41:39,492] Trial 10 finished with value: 0.5072 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 32, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 16, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 4, 'bert.encoder.layer.0.attention.output.dense_bw': 16, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 16, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 32, 'bert.encoder.layer.0.output.dense_bs': 8, 'bert.encoder.layer.0.output.dense_be': 8, 'bert.encoder.layer.1.attention.self.key_bw': 16, 'bert.encoder.layer.1.attention.self.key_bs': 16, 'bert.encoder.layer.1.attention.self.key_be': 16, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 32, 'bert.encoder.layer.1.attention.output.dense_be': 8, 'bert.encoder.layer.1.intermediate.dense_bw': 32, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 8, 'bert.encoder.layer.1.output.dense_bs': 8, 'bert.encoder.layer.1.output.dense_be': 8, 'classifier_bw': 32, 'classifier_bs': 16, 'classifier_be': 4}. Best is trial 2 with value: 0.84824.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 16:56:24,928] Trial 11 finished with value: 0.4302 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 16, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 8, 'bert.encoder.layer.0.attention.self.key_bs': 8, 'bert.encoder.layer.0.attention.self.key_be': 16, 'bert.encoder.layer.0.attention.output.dense_bw': 32, 'bert.encoder.layer.0.attention.output.dense_bs': 8, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 8, 'bert.encoder.layer.0.intermediate.dense_bs': 16, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 32, 'bert.encoder.layer.0.output.dense_bs': 16, 'bert.encoder.layer.0.output.dense_be': 16, 'bert.encoder.layer.1.attention.self.key_bw': 16, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 8, 'bert.encoder.layer.1.attention.output.dense_bs': 32, 'bert.encoder.layer.1.attention.output.dense_be': 8, 'bert.encoder.layer.1.intermediate.dense_bw': 32, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 16, 'bert.encoder.layer.1.output.dense_bs': 8, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 16, 'classifier_bs': 32, 'classifier_be': 4}. Best is trial 2 with value: 0.84824.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 17:12:22,990] Trial 12 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 32, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 8, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 16, 'bert.encoder.layer.0.attention.output.dense_bw': 32, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 16, 'bert.encoder.layer.0.intermediate.dense_bw': 8, 'bert.encoder.layer.0.intermediate.dense_bs': 16, 'bert.encoder.layer.0.intermediate.dense_be': 16, 'bert.encoder.layer.0.output.dense_bw': 32, 'bert.encoder.layer.0.output.dense_bs': 16, 'bert.encoder.layer.0.output.dense_be': 8, 'bert.encoder.layer.1.attention.self.key_bw': 16, 'bert.encoder.layer.1.attention.self.key_bs': 32, 'bert.encoder.layer.1.attention.self.key_be': 4, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 32, 'bert.encoder.layer.1.attention.output.dense_be': 8, 'bert.encoder.layer.1.intermediate.dense_bw': 32, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 16, 'bert.encoder.layer.1.output.dense_bw': 16, 'bert.encoder.layer.1.output.dense_bs': 8, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 32, 'classifier_bs': 32, 'classifier_be': 16}. Best is trial 2 with value: 0.84824.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 17:27:17,067] Trial 13 finished with value: 0.55428 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 16, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 8, 'bert.encoder.layer.0.attention.self.key_bs': 8, 'bert.encoder.layer.0.attention.self.key_be': 16, 'bert.encoder.layer.0.attention.output.dense_bw': 16, 'bert.encoder.layer.0.attention.output.dense_bs': 8, 'bert.encoder.layer.0.attention.output.dense_be': 16, 'bert.encoder.layer.0.intermediate.dense_bw': 8, 'bert.encoder.layer.0.intermediate.dense_bs': 16, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 32, 'bert.encoder.layer.0.output.dense_bs': 16, 'bert.encoder.layer.0.output.dense_be': 16, 'bert.encoder.layer.1.attention.self.key_bw': 16, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 8, 'bert.encoder.layer.1.attention.output.dense_bs': 32, 'bert.encoder.layer.1.attention.output.dense_be': 8, 'bert.encoder.layer.1.intermediate.dense_bw': 32, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 16, 'bert.encoder.layer.1.output.dense_bs': 8, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 16, 'classifier_bs': 32, 'classifier_be': 4}. Best is trial 2 with value: 0.84824.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 17:42:50,526] Trial 14 finished with value: 0.49564 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 8, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 8, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 16, 'bert.encoder.layer.0.attention.output.dense_bw': 32, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 16, 'bert.encoder.layer.0.intermediate.dense_be': 4, 'bert.encoder.layer.0.output.dense_bw': 32, 'bert.encoder.layer.0.output.dense_bs': 32, 'bert.encoder.layer.0.output.dense_be': 16, 'bert.encoder.layer.1.attention.self.key_bw': 16, 'bert.encoder.layer.1.attention.self.key_bs': 16, 'bert.encoder.layer.1.attention.self.key_be': 16, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 32, 'bert.encoder.layer.1.attention.output.dense_be': 8, 'bert.encoder.layer.1.intermediate.dense_bw': 32, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 8, 'bert.encoder.layer.1.output.dense_bw': 8, 'bert.encoder.layer.1.output.dense_bs': 8, 'bert.encoder.layer.1.output.dense_be': 8, 'classifier_bw': 32, 'classifier_bs': 32, 'classifier_be': 16}. Best is trial 2 with value: 0.84824.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 17:57:48,042] Trial 15 finished with value: 0.5316 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 16, 'bert.encoder.layer.0.attention.self.query_bs': 32, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 32, 'bert.encoder.layer.0.attention.self.key_bs': 8, 'bert.encoder.layer.0.attention.self.key_be': 16, 'bert.encoder.layer.0.attention.output.dense_bw': 32, 'bert.encoder.layer.0.attention.output.dense_bs': 8, 'bert.encoder.layer.0.attention.output.dense_be': 16, 'bert.encoder.layer.0.intermediate.dense_bw': 8, 'bert.encoder.layer.0.intermediate.dense_bs': 16, 'bert.encoder.layer.0.intermediate.dense_be': 16, 'bert.encoder.layer.0.output.dense_bw': 16, 'bert.encoder.layer.0.output.dense_bs': 8, 'bert.encoder.layer.0.output.dense_be': 16, 'bert.encoder.layer.1.attention.self.key_bw': 16, 'bert.encoder.layer.1.attention.self.key_bs': 32, 'bert.encoder.layer.1.attention.self.key_be': 4, 'bert.encoder.layer.1.attention.output.dense_bw': 8, 'bert.encoder.layer.1.attention.output.dense_bs': 32, 'bert.encoder.layer.1.attention.output.dense_be': 8, 'bert.encoder.layer.1.intermediate.dense_bw': 16, 'bert.encoder.layer.1.intermediate.dense_bs': 16, 'bert.encoder.layer.1.intermediate.dense_be': 16, 'bert.encoder.layer.1.output.dense_bw': 16, 'bert.encoder.layer.1.output.dense_bs': 16, 'bert.encoder.layer.1.output.dense_be': 4, 'classifier_bw': 32, 'classifier_bs': 8, 'classifier_be': 4}. Best is trial 2 with value: 0.84824.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 18:13:49,406] Trial 16 finished with value: 0.8486 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 16, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 8, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 4, 'bert.encoder.layer.0.attention.output.dense_bw': 32, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 16, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 32, 'bert.encoder.layer.0.output.dense_bs': 16, 'bert.encoder.layer.0.output.dense_be': 8, 'bert.encoder.layer.1.attention.self.key_bw': 32, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 32, 'bert.encoder.layer.1.attention.output.dense_be': 4, 'bert.encoder.layer.1.intermediate.dense_bw': 32, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 16, 'bert.encoder.layer.1.output.dense_bs': 8, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 16, 'classifier_bs': 32, 'classifier_be': 16}. Best is trial 16 with value: 0.8486.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 18:28:18,608] Trial 17 finished with value: 0.85524 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 8, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 4, 'bert.encoder.layer.0.attention.output.dense_bw': 16, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 16, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 32, 'bert.encoder.layer.0.output.dense_bs': 8, 'bert.encoder.layer.0.output.dense_be': 8, 'bert.encoder.layer.1.attention.self.key_bw': 32, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 8, 'bert.encoder.layer.1.attention.output.dense_be': 4, 'bert.encoder.layer.1.intermediate.dense_bw': 32, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 8, 'bert.encoder.layer.1.output.dense_bs': 8, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 16, 'classifier_bs': 32, 'classifier_be': 16}. Best is trial 17 with value: 0.85524.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 18:43:57,047] Trial 18 finished with value: 0.86772 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 32, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 4, 'bert.encoder.layer.0.attention.output.dense_bw': 16, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 8, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 8, 'bert.encoder.layer.0.output.dense_bs': 16, 'bert.encoder.layer.0.output.dense_be': 8, 'bert.encoder.layer.1.attention.self.key_bw': 32, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 8, 'bert.encoder.layer.1.attention.output.dense_be': 4, 'bert.encoder.layer.1.intermediate.dense_bw': 8, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 16, 'bert.encoder.layer.1.output.dense_bs': 32, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 16, 'classifier_bs': 32, 'classifier_be': 16}. Best is trial 18 with value: 0.86772.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 19:00:08,754] Trial 19 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 4, 'bert.encoder.layer.0.attention.self.key_bw': 32, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 4, 'bert.encoder.layer.0.attention.output.dense_bw': 16, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 8, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 8, 'bert.encoder.layer.0.output.dense_bs': 32, 'bert.encoder.layer.0.output.dense_be': 8, 'bert.encoder.layer.1.attention.self.key_bw': 32, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 8, 'bert.encoder.layer.1.attention.output.dense_be': 4, 'bert.encoder.layer.1.intermediate.dense_bw': 8, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 8, 'bert.encoder.layer.1.output.dense_bs': 32, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 16, 'classifier_bs': 32, 'classifier_be': 16}. Best is trial 18 with value: 0.86772.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 19:15:19,602] Trial 20 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 32, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 4, 'bert.encoder.layer.0.attention.output.dense_bw': 16, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 8, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 8, 'bert.encoder.layer.0.output.dense_bs': 8, 'bert.encoder.layer.0.output.dense_be': 8, 'bert.encoder.layer.1.attention.self.key_bw': 32, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 8, 'bert.encoder.layer.1.attention.output.dense_be': 4, 'bert.encoder.layer.1.intermediate.dense_bw': 8, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 8, 'bert.encoder.layer.1.output.dense_bs': 32, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 16, 'classifier_bs': 32, 'classifier_be': 16}. Best is trial 18 with value: 0.86772.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 19:30:23,239] Trial 21 finished with value: 0.86716 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 32, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 4, 'bert.encoder.layer.0.attention.output.dense_bw': 16, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 8, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 8, 'bert.encoder.layer.0.output.dense_bs': 16, 'bert.encoder.layer.0.output.dense_be': 8, 'bert.encoder.layer.1.attention.self.key_bw': 32, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 8, 'bert.encoder.layer.1.attention.output.dense_be': 4, 'bert.encoder.layer.1.intermediate.dense_bw': 8, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 16, 'bert.encoder.layer.1.output.dense_bs': 32, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 16, 'classifier_bs': 32, 'classifier_be': 16}. Best is trial 18 with value: 0.86772.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 19:44:46,396] Trial 22 finished with value: 0.86604 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 32, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 4, 'bert.encoder.layer.0.attention.output.dense_bw': 16, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 8, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 8, 'bert.encoder.layer.0.output.dense_bs': 16, 'bert.encoder.layer.0.output.dense_be': 8, 'bert.encoder.layer.1.attention.self.key_bw': 32, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 8, 'bert.encoder.layer.1.attention.output.dense_be': 4, 'bert.encoder.layer.1.intermediate.dense_bw': 8, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 16, 'bert.encoder.layer.1.output.dense_bs': 32, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 16, 'classifier_bs': 32, 'classifier_be': 16}. Best is trial 18 with value: 0.86772.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 20:01:12,903] Trial 23 finished with value: 0.8672 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 32, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 4, 'bert.encoder.layer.0.attention.output.dense_bw': 16, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 8, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 8, 'bert.encoder.layer.0.output.dense_bs': 16, 'bert.encoder.layer.0.output.dense_be': 8, 'bert.encoder.layer.1.attention.self.key_bw': 32, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 8, 'bert.encoder.layer.1.attention.output.dense_be': 4, 'bert.encoder.layer.1.intermediate.dense_bw': 8, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 16, 'bert.encoder.layer.1.output.dense_bs': 32, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 16, 'classifier_bs': 32, 'classifier_be': 16}. Best is trial 18 with value: 0.86772.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 20:17:05,163] Trial 24 finished with value: 0.86736 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 32, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 4, 'bert.encoder.layer.0.attention.output.dense_bw': 16, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 8, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 8, 'bert.encoder.layer.0.output.dense_bs': 16, 'bert.encoder.layer.0.output.dense_be': 8, 'bert.encoder.layer.1.attention.self.key_bw': 32, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 8, 'bert.encoder.layer.1.attention.output.dense_be': 4, 'bert.encoder.layer.1.intermediate.dense_bw': 8, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 16, 'bert.encoder.layer.1.output.dense_bs': 32, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 16, 'classifier_bs': 32, 'classifier_be': 16}. Best is trial 18 with value: 0.86772.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 20:33:04,656] Trial 25 finished with value: 0.87016 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 32, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 4, 'bert.encoder.layer.0.attention.output.dense_bw': 16, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 8, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 8, 'bert.encoder.layer.0.output.dense_bs': 16, 'bert.encoder.layer.0.output.dense_be': 8, 'bert.encoder.layer.1.attention.self.key_bw': 32, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 8, 'bert.encoder.layer.1.attention.output.dense_be': 4, 'bert.encoder.layer.1.intermediate.dense_bw': 8, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 16, 'bert.encoder.layer.1.output.dense_bs': 32, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 16, 'classifier_bs': 32, 'classifier_be': 16}. Best is trial 25 with value: 0.87016.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 20:49:33,502] Trial 26 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 8, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 32, 'bert.encoder.layer.0.attention.self.key_bs': 16, 'bert.encoder.layer.0.attention.self.key_be': 4, 'bert.encoder.layer.0.attention.output.dense_bw': 16, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 4, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 8, 'bert.encoder.layer.0.intermediate.dense_be': 4, 'bert.encoder.layer.0.output.dense_bw': 8, 'bert.encoder.layer.0.output.dense_bs': 16, 'bert.encoder.layer.0.output.dense_be': 8, 'bert.encoder.layer.1.attention.self.key_bw': 32, 'bert.encoder.layer.1.attention.self.key_bs': 16, 'bert.encoder.layer.1.attention.self.key_be': 16, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 8, 'bert.encoder.layer.1.attention.output.dense_be': 4, 'bert.encoder.layer.1.intermediate.dense_bw': 8, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 8, 'bert.encoder.layer.1.output.dense_bw': 16, 'bert.encoder.layer.1.output.dense_bs': 32, 'bert.encoder.layer.1.output.dense_be': 8, 'classifier_bw': 8, 'classifier_bs': 16, 'classifier_be': 8}. Best is trial 25 with value: 0.87016.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 21:05:29,222] Trial 27 finished with value: 0.86776 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 32, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 4, 'bert.encoder.layer.0.attention.output.dense_bw': 16, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 8, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 8, 'bert.encoder.layer.0.output.dense_bs': 16, 'bert.encoder.layer.0.output.dense_be': 8, 'bert.encoder.layer.1.attention.self.key_bw': 32, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 8, 'bert.encoder.layer.1.attention.output.dense_be': 4, 'bert.encoder.layer.1.intermediate.dense_bw': 8, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 16, 'bert.encoder.layer.1.output.dense_bs': 32, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 16, 'classifier_bs': 32, 'classifier_be': 16}. Best is trial 25 with value: 0.87016.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 21:21:19,348] Trial 28 finished with value: 0.86528 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 16, 'bert.encoder.layer.0.attention.self.key_bw': 32, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 4, 'bert.encoder.layer.0.attention.output.dense_bw': 16, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 8, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 8, 'bert.encoder.layer.0.output.dense_bs': 16, 'bert.encoder.layer.0.output.dense_be': 8, 'bert.encoder.layer.1.attention.self.key_bw': 32, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 8, 'bert.encoder.layer.1.attention.output.dense_be': 4, 'bert.encoder.layer.1.intermediate.dense_bw': 8, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 16, 'bert.encoder.layer.1.output.dense_bs': 32, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 16, 'classifier_bs': 32, 'classifier_be': 16}. Best is trial 25 with value: 0.87016.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 21:36:18,654] Trial 29 finished with value: 0.86328 and parameters: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 4, 'bert.encoder.layer.0.attention.self.key_bw': 32, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 4, 'bert.encoder.layer.0.attention.output.dense_bw': 16, 'bert.encoder.layer.0.attention.output.dense_bs': 16, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 8, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 8, 'bert.encoder.layer.0.output.dense_bs': 16, 'bert.encoder.layer.0.output.dense_be': 8, 'bert.encoder.layer.1.attention.self.key_bw': 32, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 16, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 8, 'bert.encoder.layer.1.attention.output.dense_be': 4, 'bert.encoder.layer.1.intermediate.dense_bw': 8, 'bert.encoder.layer.1.intermediate.dense_bs': 8, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 32, 'bert.encoder.layer.1.output.dense_bs': 32, 'bert.encoder.layer.1.output.dense_be': 8, 'classifier_bw': 16, 'classifier_bs': 32, 'classifier_be': 16}. Best is trial 25 with value: 0.87016.
[I 2026-02-05 21:36:18,912] A new study created in memory with name: bert-tiny-nas-study-LinearBlockLog

Global best Aacc history: [0.5, 0.5, 0.84824, 0.84824, 0.84824, 0.84824, 0.84824, 0.84824, 0.84824, 0.84824, 0.84824, 0.84824, 0.84824, 0.84824, 0.84824, 0.84824, 0.8486, 0.85524, 0.86772, 0.86772, 0.86772, 0.86772, 0.86772, 0.86772, 0.86772, 0.87016, 0.87016, 0.87016, 0.87016, 0.87016]
Best params: {'bert.encoder.layer.0.attention.self.query_bw': 32, 'bert.encoder.layer.0.attention.self.query_bs': 16, 'bert.encoder.layer.0.attention.self.query_be': 8, 'bert.encoder.layer.0.attention.self.key_bw': 32, 'bert.encoder.layer.0.attention.self.key_bs': 32, 'bert.encoder.layer.0.attention.self.key_be': 4, 'bert.encoder.layer.0.attention.output.dense_bw': 16, 'bert.encoder.layer.0.attention.output.dense_bs': 32, 'bert.encoder.layer.0.attention.output.dense_be': 8, 'bert.encoder.layer.0.intermediate.dense_bw': 32, 'bert.encoder.layer.0.intermediate.dense_bs': 8, 'bert.encoder.layer.0.intermediate.dense_be': 8, 'bert.encoder.layer.0.output.dense_bw': 8, 'bert.encoder.layer.0.output.dense_bs': 16, 'bert.encoder.layer.0.output.dense_be': 8, 'bert.encoder.layer.1.attention.self.key_bw': 32, 'bert.encoder.layer.1.attention.self.key_bs': 8, 'bert.encoder.layer.1.attention.self.key_be': 8, 'bert.encoder.layer.1.attention.output.dense_bw': 32, 'bert.encoder.layer.1.attention.output.dense_bs': 8, 'bert.encoder.layer.1.attention.output.dense_be': 4, 'bert.encoder.layer.1.intermediate.dense_bw': 8, 'bert.encoder.layer.1.intermediate.dense_bs': 32, 'bert.encoder.layer.1.intermediate.dense_be': 4, 'bert.encoder.layer.1.output.dense_bw': 16, 'bert.encoder.layer.1.output.dense_bs': 32, 'bert.encoder.layer.1.output.dense_be': 16, 'classifier_bw': 16, 'classifier_bs': 32, 'classifier_be': 16}
=================================================================================

 ========Starting Study for Global Precision: LinearBlockLog============

/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 21:48:04,278] Trial 0 finished with value: 0.87208 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 8, 'bert.encoder.layer.0.attention.self.query_bl_bs': 16, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 8, 'bert.encoder.layer.0.attention.self.key_bl_bs': 32, 'bert.encoder.layer.0.attention.self.key_bl_e': 8, 'bert.encoder.layer.0.attention.output.dense_bl_w': 8, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.0.attention.output.dense_bl_e': 8, 'bert.encoder.layer.0.intermediate.dense_bl_w': 32, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 8, 'bert.encoder.layer.0.intermediate.dense_bl_e': 4, 'bert.encoder.layer.0.output.dense_bl_w': 8, 'bert.encoder.layer.0.output.dense_bl_bs': 32, 'bert.encoder.layer.0.output.dense_bl_e': 8, 'bert.encoder.layer.1.attention.self.key_bl_w': 32, 'bert.encoder.layer.1.attention.self.key_bl_bs': 16, 'bert.encoder.layer.1.attention.self.key_bl_e': 8, 'bert.encoder.layer.1.attention.output.dense_bl_w': 16, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.1.attention.output.dense_bl_e': 16, 'bert.encoder.layer.1.intermediate.dense_bl_w': 8, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 16, 'bert.encoder.layer.1.intermediate.dense_bl_e': 4, 'bert.encoder.layer.1.output.dense_bl_w': 16, 'bert.encoder.layer.1.output.dense_bl_bs': 8, 'bert.encoder.layer.1.output.dense_bl_e': 8, 'classifier_bl_w': 32, 'classifier_bl_bs': 16, 'classifier_bl_e': 4}. Best is trial 0 with value: 0.87208.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 21:57:58,467] Trial 1 finished with value: 0.87244 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 16, 'bert.encoder.layer.0.attention.self.query_bl_bs': 8, 'bert.encoder.layer.0.attention.self.query_bl_e': 8, 'bert.encoder.layer.0.attention.self.key_bl_w': 16, 'bert.encoder.layer.0.attention.self.key_bl_bs': 8, 'bert.encoder.layer.0.attention.self.key_bl_e': 4, 'bert.encoder.layer.0.attention.output.dense_bl_w': 32, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bl_e': 4, 'bert.encoder.layer.0.intermediate.dense_bl_w': 32, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 16, 'bert.encoder.layer.0.intermediate.dense_bl_e': 8, 'bert.encoder.layer.0.output.dense_bl_w': 8, 'bert.encoder.layer.0.output.dense_bl_bs': 16, 'bert.encoder.layer.0.output.dense_bl_e': 16, 'bert.encoder.layer.1.attention.self.key_bl_w': 32, 'bert.encoder.layer.1.attention.self.key_bl_bs': 8, 'bert.encoder.layer.1.attention.self.key_bl_e': 4, 'bert.encoder.layer.1.attention.output.dense_bl_w': 8, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bl_e': 16, 'bert.encoder.layer.1.intermediate.dense_bl_w': 16, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 16, 'bert.encoder.layer.1.intermediate.dense_bl_e': 8, 'bert.encoder.layer.1.output.dense_bl_w': 8, 'bert.encoder.layer.1.output.dense_bl_bs': 8, 'bert.encoder.layer.1.output.dense_bl_e': 16, 'classifier_bl_w': 8, 'classifier_bl_bs': 8, 'classifier_bl_e': 16}. Best is trial 1 with value: 0.87244.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 22:06:42,461] Trial 2 finished with value: 0.87216 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 8, 'bert.encoder.layer.0.attention.self.query_bl_bs': 16, 'bert.encoder.layer.0.attention.self.query_bl_e': 8, 'bert.encoder.layer.0.attention.self.key_bl_w': 8, 'bert.encoder.layer.0.attention.self.key_bl_bs': 8, 'bert.encoder.layer.0.attention.self.key_bl_e': 8, 'bert.encoder.layer.0.attention.output.dense_bl_w': 32, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 16, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 8, 'bert.encoder.layer.0.intermediate.dense_bl_e': 16, 'bert.encoder.layer.0.output.dense_bl_w': 8, 'bert.encoder.layer.0.output.dense_bl_bs': 16, 'bert.encoder.layer.0.output.dense_bl_e': 4, 'bert.encoder.layer.1.attention.self.key_bl_w': 8, 'bert.encoder.layer.1.attention.self.key_bl_bs': 32, 'bert.encoder.layer.1.attention.self.key_bl_e': 8, 'bert.encoder.layer.1.attention.output.dense_bl_w': 8, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.1.attention.output.dense_bl_e': 16, 'bert.encoder.layer.1.intermediate.dense_bl_w': 8, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bl_e': 4, 'bert.encoder.layer.1.output.dense_bl_w': 8, 'bert.encoder.layer.1.output.dense_bl_bs': 8, 'bert.encoder.layer.1.output.dense_bl_e': 4, 'classifier_bl_w': 16, 'classifier_bl_bs': 32, 'classifier_bl_e': 8}. Best is trial 1 with value: 0.87244.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 22:18:39,331] Trial 3 finished with value: 0.87408 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 32, 'bert.encoder.layer.0.attention.self.query_bl_bs': 8, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 8, 'bert.encoder.layer.0.attention.self.key_bl_bs': 32, 'bert.encoder.layer.0.attention.self.key_bl_e': 16, 'bert.encoder.layer.0.attention.output.dense_bl_w': 32, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 8, 'bert.encoder.layer.0.output.dense_bl_w': 8, 'bert.encoder.layer.0.output.dense_bl_bs': 16, 'bert.encoder.layer.0.output.dense_bl_e': 8, 'bert.encoder.layer.1.attention.self.key_bl_w': 16, 'bert.encoder.layer.1.attention.self.key_bl_bs': 32, 'bert.encoder.layer.1.attention.self.key_bl_e': 8, 'bert.encoder.layer.1.attention.output.dense_bl_w': 8, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bl_e': 16, 'bert.encoder.layer.1.intermediate.dense_bl_w': 16, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bl_e': 4, 'bert.encoder.layer.1.output.dense_bl_w': 8, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 16, 'classifier_bl_w': 32, 'classifier_bl_bs': 8, 'classifier_bl_e': 4}. Best is trial 3 with value: 0.87408.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 22:29:50,831] Trial 4 finished with value: 0.87368 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 8, 'bert.encoder.layer.0.attention.self.query_bl_bs': 32, 'bert.encoder.layer.0.attention.self.query_bl_e': 16, 'bert.encoder.layer.0.attention.self.key_bl_w': 16, 'bert.encoder.layer.0.attention.self.key_bl_bs': 32, 'bert.encoder.layer.0.attention.self.key_bl_e': 16, 'bert.encoder.layer.0.attention.output.dense_bl_w': 16, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bl_e': 8, 'bert.encoder.layer.0.intermediate.dense_bl_w': 16, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 8, 'bert.encoder.layer.0.intermediate.dense_bl_e': 16, 'bert.encoder.layer.0.output.dense_bl_w': 8, 'bert.encoder.layer.0.output.dense_bl_bs': 16, 'bert.encoder.layer.0.output.dense_bl_e': 8, 'bert.encoder.layer.1.attention.self.key_bl_w': 32, 'bert.encoder.layer.1.attention.self.key_bl_bs': 16, 'bert.encoder.layer.1.attention.self.key_bl_e': 16, 'bert.encoder.layer.1.attention.output.dense_bl_w': 8, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.1.attention.output.dense_bl_e': 8, 'bert.encoder.layer.1.intermediate.dense_bl_w': 16, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 16, 'bert.encoder.layer.1.intermediate.dense_bl_e': 16, 'bert.encoder.layer.1.output.dense_bl_w': 8, 'bert.encoder.layer.1.output.dense_bl_bs': 16, 'bert.encoder.layer.1.output.dense_bl_e': 8, 'classifier_bl_w': 16, 'classifier_bl_bs': 8, 'classifier_bl_e': 4}. Best is trial 3 with value: 0.87408.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 22:40:58,816] Trial 5 finished with value: 0.87364 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 32, 'bert.encoder.layer.0.attention.self.query_bl_bs': 16, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 32, 'bert.encoder.layer.0.attention.self.key_bl_bs': 8, 'bert.encoder.layer.0.attention.self.key_bl_e': 8, 'bert.encoder.layer.0.attention.output.dense_bl_w': 8, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bl_e': 8, 'bert.encoder.layer.0.intermediate.dense_bl_w': 16, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 16, 'bert.encoder.layer.0.output.dense_bl_w': 8, 'bert.encoder.layer.0.output.dense_bl_bs': 16, 'bert.encoder.layer.0.output.dense_bl_e': 8, 'bert.encoder.layer.1.attention.self.key_bl_w': 32, 'bert.encoder.layer.1.attention.self.key_bl_bs': 8, 'bert.encoder.layer.1.attention.self.key_bl_e': 16, 'bert.encoder.layer.1.attention.output.dense_bl_w': 8, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bl_e': 4, 'bert.encoder.layer.1.intermediate.dense_bl_w': 16, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bl_e': 16, 'bert.encoder.layer.1.output.dense_bl_w': 8, 'bert.encoder.layer.1.output.dense_bl_bs': 16, 'bert.encoder.layer.1.output.dense_bl_e': 16, 'classifier_bl_w': 32, 'classifier_bl_bs': 16, 'classifier_bl_e': 16}. Best is trial 3 with value: 0.87408.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 22:51:17,398] Trial 6 finished with value: 0.87304 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 32, 'bert.encoder.layer.0.attention.self.query_bl_bs': 16, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 32, 'bert.encoder.layer.0.attention.self.key_bl_bs': 8, 'bert.encoder.layer.0.attention.self.key_bl_e': 4, 'bert.encoder.layer.0.attention.output.dense_bl_w': 8, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bl_e': 8, 'bert.encoder.layer.0.intermediate.dense_bl_w': 32, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 16, 'bert.encoder.layer.0.intermediate.dense_bl_e': 4, 'bert.encoder.layer.0.output.dense_bl_w': 16, 'bert.encoder.layer.0.output.dense_bl_bs': 32, 'bert.encoder.layer.0.output.dense_bl_e': 8, 'bert.encoder.layer.1.attention.self.key_bl_w': 32, 'bert.encoder.layer.1.attention.self.key_bl_bs': 16, 'bert.encoder.layer.1.attention.self.key_bl_e': 4, 'bert.encoder.layer.1.attention.output.dense_bl_w': 16, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bl_e': 8, 'bert.encoder.layer.1.intermediate.dense_bl_w': 32, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 16, 'bert.encoder.layer.1.intermediate.dense_bl_e': 16, 'bert.encoder.layer.1.output.dense_bl_w': 8, 'bert.encoder.layer.1.output.dense_bl_bs': 8, 'bert.encoder.layer.1.output.dense_bl_e': 16, 'classifier_bl_w': 32, 'classifier_bl_bs': 8, 'classifier_bl_e': 4}. Best is trial 3 with value: 0.87408.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 23:02:43,871] Trial 7 finished with value: 0.87312 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 32, 'bert.encoder.layer.0.attention.self.query_bl_bs': 32, 'bert.encoder.layer.0.attention.self.query_bl_e': 8, 'bert.encoder.layer.0.attention.self.key_bl_w': 16, 'bert.encoder.layer.0.attention.self.key_bl_bs': 8, 'bert.encoder.layer.0.attention.self.key_bl_e': 8, 'bert.encoder.layer.0.attention.output.dense_bl_w': 16, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bl_e': 4, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 8, 'bert.encoder.layer.0.intermediate.dense_bl_e': 16, 'bert.encoder.layer.0.output.dense_bl_w': 16, 'bert.encoder.layer.0.output.dense_bl_bs': 32, 'bert.encoder.layer.0.output.dense_bl_e': 16, 'bert.encoder.layer.1.attention.self.key_bl_w': 32, 'bert.encoder.layer.1.attention.self.key_bl_bs': 8, 'bert.encoder.layer.1.attention.self.key_bl_e': 8, 'bert.encoder.layer.1.attention.output.dense_bl_w': 8, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.1.attention.output.dense_bl_e': 16, 'bert.encoder.layer.1.intermediate.dense_bl_w': 16, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 16, 'bert.encoder.layer.1.intermediate.dense_bl_e': 8, 'bert.encoder.layer.1.output.dense_bl_w': 8, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 16, 'classifier_bl_w': 8, 'classifier_bl_bs': 16, 'classifier_bl_e': 4}. Best is trial 3 with value: 0.87408.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 23:13:13,038] Trial 8 finished with value: 0.87148 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 32, 'bert.encoder.layer.0.attention.self.query_bl_bs': 16, 'bert.encoder.layer.0.attention.self.query_bl_e': 8, 'bert.encoder.layer.0.attention.self.key_bl_w': 8, 'bert.encoder.layer.0.attention.self.key_bl_bs': 32, 'bert.encoder.layer.0.attention.self.key_bl_e': 16, 'bert.encoder.layer.0.attention.output.dense_bl_w': 16, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bl_e': 8, 'bert.encoder.layer.0.intermediate.dense_bl_w': 16, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 8, 'bert.encoder.layer.0.intermediate.dense_bl_e': 8, 'bert.encoder.layer.0.output.dense_bl_w': 32, 'bert.encoder.layer.0.output.dense_bl_bs': 16, 'bert.encoder.layer.0.output.dense_bl_e': 8, 'bert.encoder.layer.1.attention.self.key_bl_w': 16, 'bert.encoder.layer.1.attention.self.key_bl_bs': 32, 'bert.encoder.layer.1.attention.self.key_bl_e': 4, 'bert.encoder.layer.1.attention.output.dense_bl_w': 8, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bl_e': 8, 'bert.encoder.layer.1.intermediate.dense_bl_w': 16, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 16, 'bert.encoder.layer.1.intermediate.dense_bl_e': 4, 'bert.encoder.layer.1.output.dense_bl_w': 32, 'bert.encoder.layer.1.output.dense_bl_bs': 16, 'bert.encoder.layer.1.output.dense_bl_e': 4, 'classifier_bl_w': 32, 'classifier_bl_bs': 16, 'classifier_bl_e': 16}. Best is trial 3 with value: 0.87408.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 23:23:17,447] Trial 9 finished with value: 0.87356 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 32, 'bert.encoder.layer.0.attention.self.query_bl_bs': 16, 'bert.encoder.layer.0.attention.self.query_bl_e': 8, 'bert.encoder.layer.0.attention.self.key_bl_w': 16, 'bert.encoder.layer.0.attention.self.key_bl_bs': 8, 'bert.encoder.layer.0.attention.self.key_bl_e': 4, 'bert.encoder.layer.0.attention.output.dense_bl_w': 32, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bl_e': 4, 'bert.encoder.layer.0.intermediate.dense_bl_w': 16, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 16, 'bert.encoder.layer.0.intermediate.dense_bl_e': 16, 'bert.encoder.layer.0.output.dense_bl_w': 8, 'bert.encoder.layer.0.output.dense_bl_bs': 16, 'bert.encoder.layer.0.output.dense_bl_e': 16, 'bert.encoder.layer.1.attention.self.key_bl_w': 8, 'bert.encoder.layer.1.attention.self.key_bl_bs': 16, 'bert.encoder.layer.1.attention.self.key_bl_e': 8, 'bert.encoder.layer.1.attention.output.dense_bl_w': 32, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bl_e': 8, 'bert.encoder.layer.1.intermediate.dense_bl_w': 8, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bl_e': 8, 'bert.encoder.layer.1.output.dense_bl_w': 16, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 4, 'classifier_bl_w': 32, 'classifier_bl_bs': 32, 'classifier_bl_e': 4}. Best is trial 3 with value: 0.87408.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 23:35:07,195] Trial 10 finished with value: 0.87332 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 16, 'bert.encoder.layer.0.attention.self.query_bl_bs': 8, 'bert.encoder.layer.0.attention.self.query_bl_e': 16, 'bert.encoder.layer.0.attention.self.key_bl_w': 8, 'bert.encoder.layer.0.attention.self.key_bl_bs': 16, 'bert.encoder.layer.0.attention.self.key_bl_e': 16, 'bert.encoder.layer.0.attention.output.dense_bl_w': 32, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 8, 'bert.encoder.layer.0.output.dense_bl_w': 32, 'bert.encoder.layer.0.output.dense_bl_bs': 8, 'bert.encoder.layer.0.output.dense_bl_e': 4, 'bert.encoder.layer.1.attention.self.key_bl_w': 16, 'bert.encoder.layer.1.attention.self.key_bl_bs': 32, 'bert.encoder.layer.1.attention.self.key_bl_e': 8, 'bert.encoder.layer.1.attention.output.dense_bl_w': 32, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.1.attention.output.dense_bl_e': 4, 'bert.encoder.layer.1.intermediate.dense_bl_w': 32, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bl_e': 4, 'bert.encoder.layer.1.output.dense_bl_w': 32, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 16, 'classifier_bl_w': 8, 'classifier_bl_bs': 8, 'classifier_bl_e': 8}. Best is trial 3 with value: 0.87408.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 23:46:17,046] Trial 11 finished with value: 0.87324 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 8, 'bert.encoder.layer.0.attention.self.query_bl_bs': 32, 'bert.encoder.layer.0.attention.self.query_bl_e': 16, 'bert.encoder.layer.0.attention.self.key_bl_w': 16, 'bert.encoder.layer.0.attention.self.key_bl_bs': 32, 'bert.encoder.layer.0.attention.self.key_bl_e': 16, 'bert.encoder.layer.0.attention.output.dense_bl_w': 16, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 8, 'bert.encoder.layer.0.output.dense_bl_w': 8, 'bert.encoder.layer.0.output.dense_bl_bs': 8, 'bert.encoder.layer.0.output.dense_bl_e': 8, 'bert.encoder.layer.1.attention.self.key_bl_w': 16, 'bert.encoder.layer.1.attention.self.key_bl_bs': 16, 'bert.encoder.layer.1.attention.self.key_bl_e': 16, 'bert.encoder.layer.1.attention.output.dense_bl_w': 8, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.1.attention.output.dense_bl_e': 8, 'bert.encoder.layer.1.intermediate.dense_bl_w': 16, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bl_e': 16, 'bert.encoder.layer.1.output.dense_bl_w': 8, 'bert.encoder.layer.1.output.dense_bl_bs': 16, 'bert.encoder.layer.1.output.dense_bl_e': 8, 'classifier_bl_w': 16, 'classifier_bl_bs': 8, 'classifier_bl_e': 4}. Best is trial 3 with value: 0.87408.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-05 23:58:32,965] Trial 12 finished with value: 0.87272 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 8, 'bert.encoder.layer.0.attention.self.query_bl_bs': 32, 'bert.encoder.layer.0.attention.self.query_bl_e': 16, 'bert.encoder.layer.0.attention.self.key_bl_w': 8, 'bert.encoder.layer.0.attention.self.key_bl_bs': 32, 'bert.encoder.layer.0.attention.self.key_bl_e': 16, 'bert.encoder.layer.0.attention.output.dense_bl_w': 16, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 16, 'bert.encoder.layer.0.output.dense_bl_w': 8, 'bert.encoder.layer.0.output.dense_bl_bs': 16, 'bert.encoder.layer.0.output.dense_bl_e': 8, 'bert.encoder.layer.1.attention.self.key_bl_w': 16, 'bert.encoder.layer.1.attention.self.key_bl_bs': 32, 'bert.encoder.layer.1.attention.self.key_bl_e': 16, 'bert.encoder.layer.1.attention.output.dense_bl_w': 8, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.1.attention.output.dense_bl_e': 16, 'bert.encoder.layer.1.intermediate.dense_bl_w': 16, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bl_e': 16, 'bert.encoder.layer.1.output.dense_bl_w': 8, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 8, 'classifier_bl_w': 16, 'classifier_bl_bs': 8, 'classifier_bl_e': 4}. Best is trial 3 with value: 0.87408.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 00:09:20,881] Trial 13 finished with value: 0.87248 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 8, 'bert.encoder.layer.0.attention.self.query_bl_bs': 8, 'bert.encoder.layer.0.attention.self.query_bl_e': 16, 'bert.encoder.layer.0.attention.self.key_bl_w': 16, 'bert.encoder.layer.0.attention.self.key_bl_bs': 32, 'bert.encoder.layer.0.attention.self.key_bl_e': 16, 'bert.encoder.layer.0.attention.output.dense_bl_w': 32, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bl_e': 8, 'bert.encoder.layer.0.intermediate.dense_bl_w': 16, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 8, 'bert.encoder.layer.0.intermediate.dense_bl_e': 8, 'bert.encoder.layer.0.output.dense_bl_w': 8, 'bert.encoder.layer.0.output.dense_bl_bs': 16, 'bert.encoder.layer.0.output.dense_bl_e': 8, 'bert.encoder.layer.1.attention.self.key_bl_w': 16, 'bert.encoder.layer.1.attention.self.key_bl_bs': 32, 'bert.encoder.layer.1.attention.self.key_bl_e': 16, 'bert.encoder.layer.1.attention.output.dense_bl_w': 8, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.1.attention.output.dense_bl_e': 8, 'bert.encoder.layer.1.intermediate.dense_bl_w': 16, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bl_e': 4, 'bert.encoder.layer.1.output.dense_bl_w': 32, 'bert.encoder.layer.1.output.dense_bl_bs': 16, 'bert.encoder.layer.1.output.dense_bl_e': 8, 'classifier_bl_w': 16, 'classifier_bl_bs': 8, 'classifier_bl_e': 4}. Best is trial 3 with value: 0.87408.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 00:20:46,472] Trial 14 finished with value: 0.8738 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 16, 'bert.encoder.layer.0.attention.self.query_bl_bs': 32, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 32, 'bert.encoder.layer.0.attention.self.key_bl_bs': 16, 'bert.encoder.layer.0.attention.self.key_bl_e': 16, 'bert.encoder.layer.0.attention.output.dense_bl_w': 16, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 4, 'bert.encoder.layer.0.output.dense_bl_w': 32, 'bert.encoder.layer.0.output.dense_bl_bs': 16, 'bert.encoder.layer.0.output.dense_bl_e': 8, 'bert.encoder.layer.1.attention.self.key_bl_w': 8, 'bert.encoder.layer.1.attention.self.key_bl_bs': 16, 'bert.encoder.layer.1.attention.self.key_bl_e': 16, 'bert.encoder.layer.1.attention.output.dense_bl_w': 32, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.1.attention.output.dense_bl_e': 4, 'bert.encoder.layer.1.intermediate.dense_bl_w': 32, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bl_e': 16, 'bert.encoder.layer.1.output.dense_bl_w': 8, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 8, 'classifier_bl_w': 16, 'classifier_bl_bs': 8, 'classifier_bl_e': 4}. Best is trial 3 with value: 0.87408.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 00:31:40,441] Trial 15 finished with value: 0.8726 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 16, 'bert.encoder.layer.0.attention.self.query_bl_bs': 8, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 32, 'bert.encoder.layer.0.attention.self.key_bl_bs': 16, 'bert.encoder.layer.0.attention.self.key_bl_e': 16, 'bert.encoder.layer.0.attention.output.dense_bl_w': 32, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 4, 'bert.encoder.layer.0.output.dense_bl_w': 32, 'bert.encoder.layer.0.output.dense_bl_bs': 8, 'bert.encoder.layer.0.output.dense_bl_e': 4, 'bert.encoder.layer.1.attention.self.key_bl_w': 8, 'bert.encoder.layer.1.attention.self.key_bl_bs': 16, 'bert.encoder.layer.1.attention.self.key_bl_e': 8, 'bert.encoder.layer.1.attention.output.dense_bl_w': 32, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.1.attention.output.dense_bl_e': 4, 'bert.encoder.layer.1.intermediate.dense_bl_w': 32, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bl_e': 16, 'bert.encoder.layer.1.output.dense_bl_w': 16, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 16, 'classifier_bl_w': 32, 'classifier_bl_bs': 8, 'classifier_bl_e': 8}. Best is trial 3 with value: 0.87408.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 00:43:38,955] Trial 16 finished with value: 0.87368 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 16, 'bert.encoder.layer.0.attention.self.query_bl_bs': 8, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 32, 'bert.encoder.layer.0.attention.self.key_bl_bs': 16, 'bert.encoder.layer.0.attention.self.key_bl_e': 16, 'bert.encoder.layer.0.attention.output.dense_bl_w': 16, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 4, 'bert.encoder.layer.0.output.dense_bl_w': 32, 'bert.encoder.layer.0.output.dense_bl_bs': 16, 'bert.encoder.layer.0.output.dense_bl_e': 8, 'bert.encoder.layer.1.attention.self.key_bl_w': 8, 'bert.encoder.layer.1.attention.self.key_bl_bs': 32, 'bert.encoder.layer.1.attention.self.key_bl_e': 16, 'bert.encoder.layer.1.attention.output.dense_bl_w': 32, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.1.attention.output.dense_bl_e': 4, 'bert.encoder.layer.1.intermediate.dense_bl_w': 32, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bl_e': 4, 'bert.encoder.layer.1.output.dense_bl_w': 8, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 8, 'classifier_bl_w': 16, 'classifier_bl_bs': 32, 'classifier_bl_e': 4}. Best is trial 3 with value: 0.87408.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 00:55:24,164] Trial 17 finished with value: 0.87224 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 16, 'bert.encoder.layer.0.attention.self.query_bl_bs': 32, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 32, 'bert.encoder.layer.0.attention.self.key_bl_bs': 16, 'bert.encoder.layer.0.attention.self.key_bl_e': 16, 'bert.encoder.layer.0.attention.output.dense_bl_w': 16, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 4, 'bert.encoder.layer.0.output.dense_bl_w': 32, 'bert.encoder.layer.0.output.dense_bl_bs': 16, 'bert.encoder.layer.0.output.dense_bl_e': 8, 'bert.encoder.layer.1.attention.self.key_bl_w': 8, 'bert.encoder.layer.1.attention.self.key_bl_bs': 16, 'bert.encoder.layer.1.attention.self.key_bl_e': 8, 'bert.encoder.layer.1.attention.output.dense_bl_w': 32, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.1.attention.output.dense_bl_e': 4, 'bert.encoder.layer.1.intermediate.dense_bl_w': 32, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bl_e': 4, 'bert.encoder.layer.1.output.dense_bl_w': 8, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 16, 'classifier_bl_w': 16, 'classifier_bl_bs': 8, 'classifier_bl_e': 4}. Best is trial 3 with value: 0.87408.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 01:07:51,103] Trial 18 finished with value: 0.87328 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 32, 'bert.encoder.layer.0.attention.self.query_bl_bs': 8, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 32, 'bert.encoder.layer.0.attention.self.key_bl_bs': 16, 'bert.encoder.layer.0.attention.self.key_bl_e': 16, 'bert.encoder.layer.0.attention.output.dense_bl_w': 32, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 8, 'bert.encoder.layer.0.output.dense_bl_w': 16, 'bert.encoder.layer.0.output.dense_bl_bs': 32, 'bert.encoder.layer.0.output.dense_bl_e': 4, 'bert.encoder.layer.1.attention.self.key_bl_w': 16, 'bert.encoder.layer.1.attention.self.key_bl_bs': 32, 'bert.encoder.layer.1.attention.self.key_bl_e': 16, 'bert.encoder.layer.1.attention.output.dense_bl_w': 16, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.1.attention.output.dense_bl_e': 4, 'bert.encoder.layer.1.intermediate.dense_bl_w': 32, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bl_e': 16, 'bert.encoder.layer.1.output.dense_bl_w': 16, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 8, 'classifier_bl_w': 32, 'classifier_bl_bs': 8, 'classifier_bl_e': 16}. Best is trial 3 with value: 0.87408.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 01:19:54,153] Trial 19 finished with value: 0.87416 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 16, 'bert.encoder.layer.0.attention.self.query_bl_bs': 32, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 8, 'bert.encoder.layer.0.attention.self.key_bl_bs': 16, 'bert.encoder.layer.0.attention.self.key_bl_e': 4, 'bert.encoder.layer.0.attention.output.dense_bl_w': 8, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 4, 'bert.encoder.layer.0.output.dense_bl_w': 32, 'bert.encoder.layer.0.output.dense_bl_bs': 8, 'bert.encoder.layer.0.output.dense_bl_e': 16, 'bert.encoder.layer.1.attention.self.key_bl_w': 8, 'bert.encoder.layer.1.attention.self.key_bl_bs': 8, 'bert.encoder.layer.1.attention.self.key_bl_e': 4, 'bert.encoder.layer.1.attention.output.dense_bl_w': 32, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bl_e': 16, 'bert.encoder.layer.1.intermediate.dense_bl_w': 32, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bl_e': 8, 'bert.encoder.layer.1.output.dense_bl_w': 32, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 4, 'classifier_bl_w': 8, 'classifier_bl_bs': 32, 'classifier_bl_e': 8}. Best is trial 19 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 01:32:28,783] Trial 20 finished with value: 0.87304 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 32, 'bert.encoder.layer.0.attention.self.query_bl_bs': 32, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 8, 'bert.encoder.layer.0.attention.self.key_bl_bs': 32, 'bert.encoder.layer.0.attention.self.key_bl_e': 4, 'bert.encoder.layer.0.attention.output.dense_bl_w': 8, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 4, 'bert.encoder.layer.0.output.dense_bl_w': 32, 'bert.encoder.layer.0.output.dense_bl_bs': 8, 'bert.encoder.layer.0.output.dense_bl_e': 16, 'bert.encoder.layer.1.attention.self.key_bl_w': 8, 'bert.encoder.layer.1.attention.self.key_bl_bs': 8, 'bert.encoder.layer.1.attention.self.key_bl_e': 4, 'bert.encoder.layer.1.attention.output.dense_bl_w': 32, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bl_e': 16, 'bert.encoder.layer.1.intermediate.dense_bl_w': 8, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bl_e': 8, 'bert.encoder.layer.1.output.dense_bl_w': 32, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 4, 'classifier_bl_w': 8, 'classifier_bl_bs': 32, 'classifier_bl_e': 8}. Best is trial 19 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 01:44:38,630] Trial 21 finished with value: 0.8728 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 16, 'bert.encoder.layer.0.attention.self.query_bl_bs': 32, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 8, 'bert.encoder.layer.0.attention.self.key_bl_bs': 16, 'bert.encoder.layer.0.attention.self.key_bl_e': 4, 'bert.encoder.layer.0.attention.output.dense_bl_w': 8, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 4, 'bert.encoder.layer.0.output.dense_bl_w': 32, 'bert.encoder.layer.0.output.dense_bl_bs': 8, 'bert.encoder.layer.0.output.dense_bl_e': 16, 'bert.encoder.layer.1.attention.self.key_bl_w': 8, 'bert.encoder.layer.1.attention.self.key_bl_bs': 8, 'bert.encoder.layer.1.attention.self.key_bl_e': 4, 'bert.encoder.layer.1.attention.output.dense_bl_w': 32, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bl_e': 16, 'bert.encoder.layer.1.intermediate.dense_bl_w': 32, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bl_e': 8, 'bert.encoder.layer.1.output.dense_bl_w': 32, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 4, 'classifier_bl_w': 8, 'classifier_bl_bs': 32, 'classifier_bl_e': 8}. Best is trial 19 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 01:56:42,223] Trial 22 finished with value: 0.87256 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 16, 'bert.encoder.layer.0.attention.self.query_bl_bs': 32, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 8, 'bert.encoder.layer.0.attention.self.key_bl_bs': 16, 'bert.encoder.layer.0.attention.self.key_bl_e': 4, 'bert.encoder.layer.0.attention.output.dense_bl_w': 8, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 4, 'bert.encoder.layer.0.output.dense_bl_w': 32, 'bert.encoder.layer.0.output.dense_bl_bs': 8, 'bert.encoder.layer.0.output.dense_bl_e': 16, 'bert.encoder.layer.1.attention.self.key_bl_w': 8, 'bert.encoder.layer.1.attention.self.key_bl_bs': 8, 'bert.encoder.layer.1.attention.self.key_bl_e': 4, 'bert.encoder.layer.1.attention.output.dense_bl_w': 32, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bl_e': 16, 'bert.encoder.layer.1.intermediate.dense_bl_w': 32, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bl_e': 8, 'bert.encoder.layer.1.output.dense_bl_w': 32, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 4, 'classifier_bl_w': 8, 'classifier_bl_bs': 32, 'classifier_bl_e': 8}. Best is trial 19 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 02:08:44,794] Trial 23 finished with value: 0.87152 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 16, 'bert.encoder.layer.0.attention.self.query_bl_bs': 32, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 8, 'bert.encoder.layer.0.attention.self.key_bl_bs': 16, 'bert.encoder.layer.0.attention.self.key_bl_e': 4, 'bert.encoder.layer.0.attention.output.dense_bl_w': 8, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 4, 'bert.encoder.layer.0.output.dense_bl_w': 32, 'bert.encoder.layer.0.output.dense_bl_bs': 8, 'bert.encoder.layer.0.output.dense_bl_e': 16, 'bert.encoder.layer.1.attention.self.key_bl_w': 8, 'bert.encoder.layer.1.attention.self.key_bl_bs': 8, 'bert.encoder.layer.1.attention.self.key_bl_e': 4, 'bert.encoder.layer.1.attention.output.dense_bl_w': 32, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bl_e': 16, 'bert.encoder.layer.1.intermediate.dense_bl_w': 32, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bl_e': 8, 'bert.encoder.layer.1.output.dense_bl_w': 32, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 4, 'classifier_bl_w': 8, 'classifier_bl_bs': 32, 'classifier_bl_e': 8}. Best is trial 19 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 02:21:09,477] Trial 24 finished with value: 0.87372 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 16, 'bert.encoder.layer.0.attention.self.query_bl_bs': 32, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 8, 'bert.encoder.layer.0.attention.self.key_bl_bs': 16, 'bert.encoder.layer.0.attention.self.key_bl_e': 16, 'bert.encoder.layer.0.attention.output.dense_bl_w': 32, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 4, 'bert.encoder.layer.0.output.dense_bl_w': 32, 'bert.encoder.layer.0.output.dense_bl_bs': 16, 'bert.encoder.layer.0.output.dense_bl_e': 8, 'bert.encoder.layer.1.attention.self.key_bl_w': 8, 'bert.encoder.layer.1.attention.self.key_bl_bs': 32, 'bert.encoder.layer.1.attention.self.key_bl_e': 4, 'bert.encoder.layer.1.attention.output.dense_bl_w': 32, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bl_e': 16, 'bert.encoder.layer.1.intermediate.dense_bl_w': 32, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bl_e': 4, 'bert.encoder.layer.1.output.dense_bl_w': 8, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 4, 'classifier_bl_w': 16, 'classifier_bl_bs': 8, 'classifier_bl_e': 4}. Best is trial 19 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 02:31:56,471] Trial 25 finished with value: 0.87052 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 16, 'bert.encoder.layer.0.attention.self.query_bl_bs': 8, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 32, 'bert.encoder.layer.0.attention.self.key_bl_bs': 16, 'bert.encoder.layer.0.attention.self.key_bl_e': 4, 'bert.encoder.layer.0.attention.output.dense_bl_w': 8, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 32, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 16, 'bert.encoder.layer.0.intermediate.dense_bl_e': 8, 'bert.encoder.layer.0.output.dense_bl_w': 16, 'bert.encoder.layer.0.output.dense_bl_bs': 8, 'bert.encoder.layer.0.output.dense_bl_e': 16, 'bert.encoder.layer.1.attention.self.key_bl_w': 16, 'bert.encoder.layer.1.attention.self.key_bl_bs': 8, 'bert.encoder.layer.1.attention.self.key_bl_e': 8, 'bert.encoder.layer.1.attention.output.dense_bl_w': 16, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.1.attention.output.dense_bl_e': 4, 'bert.encoder.layer.1.intermediate.dense_bl_w': 32, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bl_e': 16, 'bert.encoder.layer.1.output.dense_bl_w': 32, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 16, 'classifier_bl_w': 8, 'classifier_bl_bs': 32, 'classifier_bl_e': 8}. Best is trial 19 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 02:43:44,439] Trial 26 finished with value: 0.87276 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 16, 'bert.encoder.layer.0.attention.self.query_bl_bs': 32, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 8, 'bert.encoder.layer.0.attention.self.key_bl_bs': 16, 'bert.encoder.layer.0.attention.self.key_bl_e': 16, 'bert.encoder.layer.0.attention.output.dense_bl_w': 16, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bl_e': 4, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 4, 'bert.encoder.layer.0.output.dense_bl_w': 32, 'bert.encoder.layer.0.output.dense_bl_bs': 16, 'bert.encoder.layer.0.output.dense_bl_e': 8, 'bert.encoder.layer.1.attention.self.key_bl_w': 8, 'bert.encoder.layer.1.attention.self.key_bl_bs': 16, 'bert.encoder.layer.1.attention.self.key_bl_e': 16, 'bert.encoder.layer.1.attention.output.dense_bl_w': 32, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bl_e': 16, 'bert.encoder.layer.1.intermediate.dense_bl_w': 32, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bl_e': 8, 'bert.encoder.layer.1.output.dense_bl_w': 8, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 8, 'classifier_bl_w': 32, 'classifier_bl_bs': 8, 'classifier_bl_e': 4}. Best is trial 19 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 02:54:54,800] Trial 27 finished with value: 0.87308 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 32, 'bert.encoder.layer.0.attention.self.query_bl_bs': 8, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 32, 'bert.encoder.layer.0.attention.self.key_bl_bs': 32, 'bert.encoder.layer.0.attention.self.key_bl_e': 4, 'bert.encoder.layer.0.attention.output.dense_bl_w': 16, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 8, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 8, 'bert.encoder.layer.0.output.dense_bl_w': 32, 'bert.encoder.layer.0.output.dense_bl_bs': 16, 'bert.encoder.layer.0.output.dense_bl_e': 4, 'bert.encoder.layer.1.attention.self.key_bl_w': 16, 'bert.encoder.layer.1.attention.self.key_bl_bs': 8, 'bert.encoder.layer.1.attention.self.key_bl_e': 4, 'bert.encoder.layer.1.attention.output.dense_bl_w': 32, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.1.attention.output.dense_bl_e': 4, 'bert.encoder.layer.1.intermediate.dense_bl_w': 8, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bl_e': 16, 'bert.encoder.layer.1.output.dense_bl_w': 8, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 4, 'classifier_bl_w': 32, 'classifier_bl_bs': 8, 'classifier_bl_e': 4}. Best is trial 19 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:07:16,116] Trial 28 finished with value: 0.87352 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 16, 'bert.encoder.layer.0.attention.self.query_bl_bs': 32, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 8, 'bert.encoder.layer.0.attention.self.key_bl_bs': 16, 'bert.encoder.layer.0.attention.self.key_bl_e': 8, 'bert.encoder.layer.0.attention.output.dense_bl_w': 32, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 4, 'bert.encoder.layer.0.output.dense_bl_w': 16, 'bert.encoder.layer.0.output.dense_bl_bs': 32, 'bert.encoder.layer.0.output.dense_bl_e': 8, 'bert.encoder.layer.1.attention.self.key_bl_w': 8, 'bert.encoder.layer.1.attention.self.key_bl_bs': 32, 'bert.encoder.layer.1.attention.self.key_bl_e': 8, 'bert.encoder.layer.1.attention.output.dense_bl_w': 16, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bl_e': 16, 'bert.encoder.layer.1.intermediate.dense_bl_w': 32, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bl_e': 8, 'bert.encoder.layer.1.output.dense_bl_w': 16, 'bert.encoder.layer.1.output.dense_bl_bs': 8, 'bert.encoder.layer.1.output.dense_bl_e': 16, 'classifier_bl_w': 8, 'classifier_bl_bs': 16, 'classifier_bl_e': 16}. Best is trial 19 with value: 0.87416.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:18:35,755] Trial 29 finished with value: 0.87404 and parameters: {'bert.encoder.layer.0.attention.self.query_bl_w': 32, 'bert.encoder.layer.0.attention.self.query_bl_bs': 8, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 8, 'bert.encoder.layer.0.attention.self.key_bl_bs': 32, 'bert.encoder.layer.0.attention.self.key_bl_e': 16, 'bert.encoder.layer.0.attention.output.dense_bl_w': 8, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.0.attention.output.dense_bl_e': 4, 'bert.encoder.layer.0.intermediate.dense_bl_w': 32, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 16, 'bert.encoder.layer.0.intermediate.dense_bl_e': 4, 'bert.encoder.layer.0.output.dense_bl_w': 32, 'bert.encoder.layer.0.output.dense_bl_bs': 8, 'bert.encoder.layer.0.output.dense_bl_e': 16, 'bert.encoder.layer.1.attention.self.key_bl_w': 16, 'bert.encoder.layer.1.attention.self.key_bl_bs': 16, 'bert.encoder.layer.1.attention.self.key_bl_e': 16, 'bert.encoder.layer.1.attention.output.dense_bl_w': 32, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.1.attention.output.dense_bl_e': 16, 'bert.encoder.layer.1.intermediate.dense_bl_w': 16, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 8, 'bert.encoder.layer.1.intermediate.dense_bl_e': 4, 'bert.encoder.layer.1.output.dense_bl_w': 32, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 8, 'classifier_bl_w': 16, 'classifier_bl_bs': 32, 'classifier_bl_e': 8}. Best is trial 19 with value: 0.87416.
[I 2026-02-06 03:18:35,981] A new study created in memory with name: bert-tiny-nas-study-LinearBinary

Global best Aacc history: [0.87208, 0.87244, 0.87244, 0.87408, 0.87408, 0.87408, 0.87408, 0.87408, 0.87408, 0.87408, 0.87408, 0.87408, 0.87408, 0.87408, 0.87408, 0.87408, 0.87408, 0.87408, 0.87408, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416, 0.87416]
Best params: {'bert.encoder.layer.0.attention.self.query_bl_w': 16, 'bert.encoder.layer.0.attention.self.query_bl_bs': 32, 'bert.encoder.layer.0.attention.self.query_bl_e': 4, 'bert.encoder.layer.0.attention.self.key_bl_w': 8, 'bert.encoder.layer.0.attention.self.key_bl_bs': 16, 'bert.encoder.layer.0.attention.self.key_bl_e': 4, 'bert.encoder.layer.0.attention.output.dense_bl_w': 8, 'bert.encoder.layer.0.attention.output.dense_bl_bs': 32, 'bert.encoder.layer.0.attention.output.dense_bl_e': 16, 'bert.encoder.layer.0.intermediate.dense_bl_w': 8, 'bert.encoder.layer.0.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.0.intermediate.dense_bl_e': 4, 'bert.encoder.layer.0.output.dense_bl_w': 32, 'bert.encoder.layer.0.output.dense_bl_bs': 8, 'bert.encoder.layer.0.output.dense_bl_e': 16, 'bert.encoder.layer.1.attention.self.key_bl_w': 8, 'bert.encoder.layer.1.attention.self.key_bl_bs': 8, 'bert.encoder.layer.1.attention.self.key_bl_e': 4, 'bert.encoder.layer.1.attention.output.dense_bl_w': 32, 'bert.encoder.layer.1.attention.output.dense_bl_bs': 16, 'bert.encoder.layer.1.attention.output.dense_bl_e': 16, 'bert.encoder.layer.1.intermediate.dense_bl_w': 32, 'bert.encoder.layer.1.intermediate.dense_bl_bs': 32, 'bert.encoder.layer.1.intermediate.dense_bl_e': 8, 'bert.encoder.layer.1.output.dense_bl_w': 32, 'bert.encoder.layer.1.output.dense_bl_bs': 32, 'bert.encoder.layer.1.output.dense_bl_e': 4, 'classifier_bl_w': 8, 'classifier_bl_bs': 32, 'classifier_bl_e': 8}
=================================================================================

 ========Starting Study for Global Precision: LinearBinary============

/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:20:25,351] Trial 0 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 8, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.self.key_width': 32, 'bert.encoder.layer.0.attention.self.key_frac': 2, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_width': 32, 'bert.encoder.layer.0.intermediate.dense_frac': 2, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 2, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 2, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 16, 'bert.encoder.layer.1.output.dense_frac': 8, 'classifier_bipolar': True, 'classifier_width': 16, 'classifier_frac': 2}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:22:11,752] Trial 1 finished with value: 0.79092 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 2, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 8, 'classifier_bipolar': True, 'classifier_width': 8, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:23:56,482] Trial 2 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_frac': 2, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 2, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.output.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 4, 'classifier_bipolar': False, 'classifier_width': 16, 'classifier_frac': 4}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:25:40,857] Trial 3 finished with value: 0.67124 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 2, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 32, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 2, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 32, 'bert.encoder.layer.1.attention.self.key_frac': 2, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 4, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 2, 'bert.encoder.layer.1.output.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_width': 16, 'bert.encoder.layer.1.output.dense_frac': 2, 'classifier_bipolar': False, 'classifier_width': 8, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:27:30,250] Trial 4 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.self.key_width': 32, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_width': 32, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 2, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 2, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 16, 'bert.encoder.layer.1.output.dense_frac': 8, 'classifier_bipolar': True, 'classifier_width': 8, 'classifier_frac': 4}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:29:15,498] Trial 5 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 8, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_frac': 2, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.self.key_width': 32, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 2, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_width': 16, 'bert.encoder.layer.1.output.dense_frac': 8, 'classifier_bipolar': True, 'classifier_width': 16, 'classifier_frac': 4}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:31:01,318] Trial 6 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 8, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 2, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_width': 32, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_frac': 2, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.self.key_width': 32, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 8, 'bert.encoder.layer.1.attention.output.dense_frac': 2, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 4, 'classifier_bipolar': False, 'classifier_width': 8, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:32:49,088] Trial 7 finished with value: 0.52856 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 8, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.self.key_width': 32, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_width': 32, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 2, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 32, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 4, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 16, 'bert.encoder.layer.1.output.dense_frac': 2, 'classifier_bipolar': True, 'classifier_width': 16, 'classifier_frac': 2}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:34:35,960] Trial 8 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_frac': 2, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_frac': 2, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 16, 'bert.encoder.layer.1.output.dense_frac': 2, 'classifier_bipolar': True, 'classifier_width': 8, 'classifier_frac': 4}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:36:21,294] Trial 9 finished with value: 0.51036 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 2, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.self.key_width': 32, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 2, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 8, 'bert.encoder.layer.1.attention.output.dense_frac': 2, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_frac': 2, 'bert.encoder.layer.1.output.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 2, 'classifier_bipolar': True, 'classifier_width': 8, 'classifier_frac': 2}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:38:03,675] Trial 10 finished with value: 0.30332 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 8, 'classifier_bipolar': False, 'classifier_width': 32, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:39:47,626] Trial 11 finished with value: 0.78176 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 2, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 2, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 32, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 4, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 2, 'bert.encoder.layer.1.output.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 2, 'classifier_bipolar': False, 'classifier_width': 8, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:41:30,399] Trial 12 finished with value: 0.78176 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 2, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 2, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 32, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 4, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 2, 'bert.encoder.layer.1.output.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 8, 'classifier_bipolar': False, 'classifier_width': 32, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:43:10,985] Trial 13 finished with value: 0.78176 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 2, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 2, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 4, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_frac': 2, 'bert.encoder.layer.1.output.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 2, 'classifier_bipolar': False, 'classifier_width': 8, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:44:57,717] Trial 14 finished with value: 0.78292 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 4, 'classifier_bipolar': True, 'classifier_width': 8, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:46:44,500] Trial 15 finished with value: 0.78292 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 4, 'classifier_bipolar': True, 'classifier_width': 8, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:48:31,280] Trial 16 finished with value: 0.78292 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 4, 'classifier_bipolar': True, 'classifier_width': 32, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:50:18,099] Trial 17 finished with value: 0.78292 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 8, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 4, 'classifier_bipolar': True, 'classifier_width': 8, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:52:03,296] Trial 18 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 2, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 8, 'classifier_bipolar': True, 'classifier_width': 8, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:53:49,669] Trial 19 finished with value: 0.78292 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 2, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 4, 'classifier_bipolar': True, 'classifier_width': 32, 'classifier_frac': 2}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:55:36,789] Trial 20 finished with value: 0.78292 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 8, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 8, 'classifier_bipolar': True, 'classifier_width': 8, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:57:23,340] Trial 21 finished with value: 0.78292 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 4, 'classifier_bipolar': True, 'classifier_width': 8, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 03:59:13,464] Trial 22 finished with value: 0.78292 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 4, 'classifier_bipolar': True, 'classifier_width': 8, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:01:01,397] Trial 23 finished with value: 0.78292 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 4, 'classifier_bipolar': True, 'classifier_width': 8, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:02:48,254] Trial 24 finished with value: 0.78292 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 4, 'classifier_bipolar': True, 'classifier_width': 8, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:04:38,203] Trial 25 finished with value: 0.78292 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 2, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 4, 'classifier_bipolar': True, 'classifier_width': 8, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:06:26,086] Trial 26 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 4, 'classifier_bipolar': True, 'classifier_width': 8, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:08:12,750] Trial 27 finished with value: 0.78292 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 8, 'classifier_bipolar': True, 'classifier_width': 8, 'classifier_frac': 8}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:09:56,729] Trial 28 finished with value: 0.79092 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 8, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 2, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_frac': 2, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 8, 'bert.encoder.layer.1.attention.output.dense_frac': 2, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 4, 'classifier_bipolar': True, 'classifier_width': 32, 'classifier_frac': 4}. Best is trial 1 with value: 0.79092.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:11:40,676] Trial 29 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 8, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 2, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_frac': 2, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_width': 8, 'bert.encoder.layer.1.attention.output.dense_frac': 2, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 8, 'classifier_bipolar': True, 'classifier_width': 32, 'classifier_frac': 4}. Best is trial 1 with value: 0.79092.
[I 2026-02-06 04:11:40,881] A new study created in memory with name: bert-tiny-nas-study-LinearBinaryScaling

Global best Aacc history: [0.5, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092, 0.79092]
Best params: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 2, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.output.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 8, 'classifier_bipolar': True, 'classifier_width': 8, 'classifier_frac': 8}
=================================================================================

 ========Starting Study for Global Precision: LinearBinaryScaling============

/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:13:58,142] Trial 0 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': False}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:16:20,628] Trial 1 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': True}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:18:48,866] Trial 2 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': False}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:21:15,826] Trial 3 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': False}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:23:41,793] Trial 4 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': True, 'classifier_bipolar': True}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:26:01,629] Trial 5 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': True, 'classifier_bipolar': True}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:28:25,590] Trial 6 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': True}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:30:51,930] Trial 7 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': True, 'classifier_bipolar': False}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:33:15,361] Trial 8 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': True}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:35:40,228] Trial 9 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_bipolar': True, 'classifier_bipolar': True}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:38:00,351] Trial 10 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': False}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:40:24,168] Trial 11 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': False}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:42:49,448] Trial 12 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': True}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:45:12,222] Trial 13 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': False}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:47:38,334] Trial 14 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': True}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:50:03,584] Trial 15 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': False}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:52:23,260] Trial 16 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': True}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:54:48,048] Trial 17 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': False}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:56:57,171] Trial 18 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_bipolar': True, 'classifier_bipolar': False}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 04:59:17,172] Trial 19 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': True}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:01:41,104] Trial 20 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': True}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:04:07,374] Trial 21 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': False}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:06:32,481] Trial 22 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': False}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:09:00,746] Trial 23 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': False}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:11:20,417] Trial 24 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': False}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:13:38,253] Trial 25 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': False}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:16:03,318] Trial 26 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_bipolar': True, 'classifier_bipolar': False}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:18:31,548] Trial 27 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': True, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.self.key_bipolar': False, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': False}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:21:00,162] Trial 28 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_bipolar': False, 'bert.encoder.layer.1.intermediate.dense_bipolar': True, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': True}. Best is trial 0 with value: 0.5.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:23:28,771] Trial 29 finished with value: 0.5 and parameters: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.key_bipolar': False, 'bert.encoder.layer.0.attention.output.dense_bipolar': False, 'bert.encoder.layer.0.intermediate.dense_bipolar': True, 'bert.encoder.layer.0.output.dense_bipolar': False, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': False}. Best is trial 0 with value: 0.5.
[I 2026-02-06 05:23:28,940] A new study created in memory with name: bert-tiny-nas-study-LinearTernary

Global best Aacc history: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
Best params: {'bert.encoder.layer.0.attention.self.query_bipolar': False, 'bert.encoder.layer.0.attention.self.key_bipolar': True, 'bert.encoder.layer.0.attention.output.dense_bipolar': True, 'bert.encoder.layer.0.intermediate.dense_bipolar': False, 'bert.encoder.layer.0.output.dense_bipolar': True, 'bert.encoder.layer.1.attention.self.key_bipolar': True, 'bert.encoder.layer.1.attention.output.dense_bipolar': True, 'bert.encoder.layer.1.intermediate.dense_bipolar': False, 'bert.encoder.layer.1.output.dense_bipolar': False, 'classifier_bipolar': False}
=================================================================================

 ========Starting Study for Global Precision: LinearTernary============

/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:25:32,214] Trial 0 finished with value: 0.77952 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 2, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.self.key_scaling': False, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 8, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_scaling': False, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 2, 'bert.encoder.layer.0.output.dense_scaling': False, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 2, 'bert.encoder.layer.1.attention.self.key_scaling': False, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': True, 'bert.encoder.layer.1.output.dense_width': 16, 'bert.encoder.layer.1.output.dense_frac': 8, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 16, 'classifier_frac': 8, 'classifier_scaling': True}. Best is trial 0 with value: 0.77952.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:27:36,157] Trial 1 finished with value: 0.78028 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 2, 'bert.encoder.layer.0.attention.self.query_scaling': False, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 8, 'bert.encoder.layer.0.attention.output.dense_scaling': True, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': False, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 2, 'bert.encoder.layer.0.output.dense_scaling': True, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 2, 'bert.encoder.layer.1.attention.self.key_scaling': False, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 4, 'bert.encoder.layer.1.attention.output.dense_scaling': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 8, 'bert.encoder.layer.1.output.dense_scaling': True, 'classifier_width': 16, 'classifier_frac': 2, 'classifier_scaling': False}. Best is trial 1 with value: 0.78028.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:29:39,871] Trial 2 finished with value: 0.85512 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': False, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': False, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': True, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': True, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 8, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.intermediate.dense_scaling': True, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 4, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 32, 'classifier_frac': 4, 'classifier_scaling': True}. Best is trial 2 with value: 0.85512.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:31:48,641] Trial 3 finished with value: 0.77568 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': False, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': False, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': True, 'bert.encoder.layer.0.intermediate.dense_width': 32, 'bert.encoder.layer.0.intermediate.dense_frac': 2, 'bert.encoder.layer.0.intermediate.dense_scaling': False, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': True, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.self.key_scaling': False, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 4, 'bert.encoder.layer.1.attention.output.dense_scaling': False, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.intermediate.dense_scaling': True, 'bert.encoder.layer.1.output.dense_width': 16, 'bert.encoder.layer.1.output.dense_frac': 4, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 16, 'classifier_frac': 2, 'classifier_scaling': True}. Best is trial 2 with value: 0.85512.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:33:52,333] Trial 4 finished with value: 0.79704 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 2, 'bert.encoder.layer.0.attention.self.query_scaling': False, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 2, 'bert.encoder.layer.0.attention.self.key_scaling': False, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.attention.output.dense_scaling': True, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': True, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': False, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 4, 'bert.encoder.layer.1.attention.output.dense_scaling': False, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': True, 'bert.encoder.layer.1.output.dense_width': 16, 'bert.encoder.layer.1.output.dense_frac': 8, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 16, 'classifier_frac': 4, 'classifier_scaling': True}. Best is trial 2 with value: 0.85512.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:35:54,423] Trial 5 finished with value: 0.87508 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 2, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 8, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': False, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 2, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 4, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 2, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 32, 'classifier_frac': 4, 'classifier_scaling': True}. Best is trial 5 with value: 0.87508.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:37:57,281] Trial 6 finished with value: 0.87076 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 2, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 32, 'bert.encoder.layer.0.intermediate.dense_frac': 2, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.0.output.dense_scaling': False, 'bert.encoder.layer.1.attention.self.key_width': 32, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.self.key_scaling': False, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': False, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.intermediate.dense_scaling': True, 'bert.encoder.layer.1.output.dense_width': 16, 'bert.encoder.layer.1.output.dense_frac': 2, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 32, 'classifier_frac': 8, 'classifier_scaling': True}. Best is trial 5 with value: 0.87508.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:40:01,394] Trial 7 finished with value: 0.8746 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 2, 'bert.encoder.layer.0.intermediate.dense_scaling': False, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': True, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': False, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 2, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 32, 'classifier_frac': 4, 'classifier_scaling': True}. Best is trial 5 with value: 0.87508.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:42:06,904] Trial 8 finished with value: 0.83656 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 32, 'bert.encoder.layer.0.attention.self.query_frac': 2, 'bert.encoder.layer.0.attention.self.query_scaling': False, 'bert.encoder.layer.0.attention.self.key_width': 32, 'bert.encoder.layer.0.attention.self.key_frac': 2, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 32, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 2, 'bert.encoder.layer.0.output.dense_scaling': True, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 2, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 4, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.intermediate.dense_scaling': True, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 2, 'bert.encoder.layer.1.output.dense_scaling': True, 'classifier_width': 16, 'classifier_frac': 8, 'classifier_scaling': True}. Best is trial 5 with value: 0.87508.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:44:13,381] Trial 9 finished with value: 0.78776 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': False, 'bert.encoder.layer.0.attention.self.key_width': 8, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_frac': 8, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_frac': 2, 'bert.encoder.layer.0.intermediate.dense_scaling': False, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': False, 'bert.encoder.layer.1.attention.self.key_width': 32, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.self.key_scaling': False, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 4, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_frac': 4, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 8, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 32, 'classifier_frac': 4, 'classifier_scaling': True}. Best is trial 5 with value: 0.87508.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:46:21,375] Trial 10 finished with value: 0.87324 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 8, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 32, 'bert.encoder.layer.0.attention.self.key_frac': 4, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 8, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 16, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 32, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.0.output.dense_scaling': False, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 2, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 8, 'bert.encoder.layer.1.attention.output.dense_frac': 2, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 2, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 2, 'bert.encoder.layer.1.output.dense_scaling': True, 'classifier_width': 8, 'classifier_frac': 4, 'classifier_scaling': False}. Best is trial 5 with value: 0.87508.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:48:25,220] Trial 11 finished with value: 0.8746 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 8, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 2, 'bert.encoder.layer.0.intermediate.dense_scaling': False, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': False, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 2, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 8, 'bert.encoder.layer.1.output.dense_frac': 2, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 32, 'classifier_frac': 4, 'classifier_scaling': False}. Best is trial 5 with value: 0.87508.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:50:28,449] Trial 12 finished with value: 0.87572 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': True, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 2, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 32, 'classifier_frac': 4, 'classifier_scaling': True}. Best is trial 12 with value: 0.87572.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:52:34,985] Trial 13 finished with value: 0.87784 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': False, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 2, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 8, 'classifier_frac': 4, 'classifier_scaling': True}. Best is trial 13 with value: 0.87784.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:54:41,037] Trial 14 finished with value: 0.875 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': True, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_frac': 2, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 2, 'bert.encoder.layer.1.output.dense_scaling': True, 'classifier_width': 8, 'classifier_frac': 4, 'classifier_scaling': False}. Best is trial 13 with value: 0.87784.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:56:49,409] Trial 15 finished with value: 0.87456 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.0.output.dense_scaling': False, 'bert.encoder.layer.1.attention.self.key_width': 32, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 8, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 2, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 8, 'classifier_frac': 2, 'classifier_scaling': True}. Best is trial 13 with value: 0.87784.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 05:58:54,739] Trial 16 finished with value: 0.87576 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': True, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 4, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 8, 'classifier_frac': 4, 'classifier_scaling': True}. Best is trial 13 with value: 0.87784.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 06:00:58,697] Trial 17 finished with value: 0.874 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': False, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 2, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 4, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 8, 'classifier_frac': 4, 'classifier_scaling': True}. Best is trial 13 with value: 0.87784.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 06:03:04,268] Trial 18 finished with value: 0.858 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 8, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 32, 'bert.encoder.layer.0.attention.self.key_frac': 2, 'bert.encoder.layer.0.attention.self.key_scaling': False, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': True, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_frac': 2, 'bert.encoder.layer.0.output.dense_scaling': True, 'bert.encoder.layer.1.attention.self.key_width': 32, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 8, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 2, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 4, 'bert.encoder.layer.1.output.dense_scaling': True, 'classifier_width': 8, 'classifier_frac': 2, 'classifier_scaling': False}. Best is trial 13 with value: 0.87784.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 06:05:10,810] Trial 19 finished with value: 0.87564 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.0.output.dense_scaling': False, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 4, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 8, 'classifier_frac': 8, 'classifier_scaling': True}. Best is trial 13 with value: 0.87784.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 06:07:25,589] Trial 20 finished with value: 0.875 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 32, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': False, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 4, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 8, 'classifier_frac': 4, 'classifier_scaling': True}. Best is trial 13 with value: 0.87784.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 06:09:33,177] Trial 21 finished with value: 0.87436 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': True, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 2, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 8, 'classifier_frac': 4, 'classifier_scaling': True}. Best is trial 13 with value: 0.87784.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 06:11:39,026] Trial 22 finished with value: 0.87404 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 32, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': True, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 2, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 8, 'classifier_frac': 4, 'classifier_scaling': True}. Best is trial 13 with value: 0.87784.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 06:13:42,924] Trial 23 finished with value: 0.87584 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': True, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 4, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 8, 'classifier_frac': 4, 'classifier_scaling': True}. Best is trial 13 with value: 0.87784.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 06:15:44,640] Trial 24 finished with value: 0.87756 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': True, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 4, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 8, 'classifier_frac': 4, 'classifier_scaling': True}. Best is trial 13 with value: 0.87784.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 06:17:52,594] Trial 25 finished with value: 0.87296 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 8, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 32, 'bert.encoder.layer.0.attention.self.key_frac': 2, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': True, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 2, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 32, 'bert.encoder.layer.1.intermediate.dense_frac': 2, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 4, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 8, 'classifier_frac': 4, 'classifier_scaling': True}. Best is trial 13 with value: 0.87784.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 06:19:57,710] Trial 26 finished with value: 0.858 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': False, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': True, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': True, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': False, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 4, 'bert.encoder.layer.1.output.dense_scaling': True, 'classifier_width': 8, 'classifier_frac': 4, 'classifier_scaling': False}. Best is trial 13 with value: 0.87784.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 06:22:06,400] Trial 27 finished with value: 0.87404 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 2, 'bert.encoder.layer.0.output.dense_scaling': True, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 4, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 8, 'classifier_frac': 4, 'classifier_scaling': True}. Best is trial 13 with value: 0.87784.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 06:24:13,247] Trial 28 finished with value: 0.87652 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 8, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 32, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.0.output.dense_scaling': False, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 16, 'bert.encoder.layer.1.output.dense_frac': 4, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 8, 'classifier_frac': 8, 'classifier_scaling': True}. Best is trial 13 with value: 0.87784.
/home/testunot/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-02-06 06:26:15,093] Trial 29 finished with value: 0.83328 and parameters: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 8, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 32, 'bert.encoder.layer.0.attention.self.key_frac': 2, 'bert.encoder.layer.0.attention.self.key_scaling': False, 'bert.encoder.layer.0.attention.output.dense_width': 16, 'bert.encoder.layer.0.attention.output.dense_frac': 4, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 32, 'bert.encoder.layer.0.intermediate.dense_frac': 4, 'bert.encoder.layer.0.intermediate.dense_scaling': False, 'bert.encoder.layer.0.output.dense_width': 16, 'bert.encoder.layer.0.output.dense_frac': 8, 'bert.encoder.layer.0.output.dense_scaling': False, 'bert.encoder.layer.1.attention.self.key_width': 8, 'bert.encoder.layer.1.attention.self.key_frac': 8, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 32, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 16, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': True, 'bert.encoder.layer.1.output.dense_width': 16, 'bert.encoder.layer.1.output.dense_frac': 8, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 8, 'classifier_frac': 8, 'classifier_scaling': True}. Best is trial 13 with value: 0.87784.

Global best Aacc history: [0.77952, 0.78028, 0.85512, 0.85512, 0.85512, 0.87508, 0.87508, 0.87508, 0.87508, 0.87508, 0.87508, 0.87508, 0.87572, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784]
Best params: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': False, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 2, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 8, 'classifier_frac': 4, 'classifier_scaling': True}
=================================================================================

Global best Aacc history: [0.77952, 0.78028, 0.85512, 0.85512, 0.85512, 0.87508, 0.87508, 0.87508, 0.87508, 0.87508, 0.87508, 0.87508, 0.87572, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784, 0.87784]
Best params: {'bert.encoder.layer.0.attention.self.query_width': 16, 'bert.encoder.layer.0.attention.self.query_frac': 4, 'bert.encoder.layer.0.attention.self.query_scaling': True, 'bert.encoder.layer.0.attention.self.key_width': 16, 'bert.encoder.layer.0.attention.self.key_frac': 8, 'bert.encoder.layer.0.attention.self.key_scaling': True, 'bert.encoder.layer.0.attention.output.dense_width': 8, 'bert.encoder.layer.0.attention.output.dense_frac': 2, 'bert.encoder.layer.0.attention.output.dense_scaling': False, 'bert.encoder.layer.0.intermediate.dense_width': 8, 'bert.encoder.layer.0.intermediate.dense_frac': 8, 'bert.encoder.layer.0.intermediate.dense_scaling': True, 'bert.encoder.layer.0.output.dense_width': 8, 'bert.encoder.layer.0.output.dense_frac': 4, 'bert.encoder.layer.0.output.dense_scaling': False, 'bert.encoder.layer.1.attention.self.key_width': 16, 'bert.encoder.layer.1.attention.self.key_frac': 4, 'bert.encoder.layer.1.attention.self.key_scaling': True, 'bert.encoder.layer.1.attention.output.dense_width': 16, 'bert.encoder.layer.1.attention.output.dense_frac': 8, 'bert.encoder.layer.1.attention.output.dense_scaling': True, 'bert.encoder.layer.1.intermediate.dense_width': 8, 'bert.encoder.layer.1.intermediate.dense_frac': 8, 'bert.encoder.layer.1.intermediate.dense_scaling': False, 'bert.encoder.layer.1.output.dense_width': 32, 'bert.encoder.layer.1.output.dense_frac': 2, 'bert.encoder.layer.1.output.dense_scaling': False, 'classifier_width': 8, 'classifier_frac': 4, 'classifier_scaling': True}